### ISSUE TITLE
How to run an existing keras model on a massive dataset using Spark ?

### ISSUE THREAD

**Issue by shaktisd** [maxpumperla/elephas#101]
I have a keras deep learning model and I have to now process a large dataset over it and calculate the results. This model is already trained, so training is not an issue. I tried exposing my model as a REST service and then calling the same via spark is working fine,but there is a latency factor and for a huge dataset this is a problem. Is there an example someone can quote which I can use as a reference to use my keras model in pyspark and process data by direct python calls instead of REST calls in a spark environment.

**Comment by maxpumperla** [comment]
that's a little too vague for me to answer. Of course the Spark setup comes with an overhead. what does "massive" mean here? do you want to do batch prediction for very large batches? If you have a truly out-of-memory data set to predict on, you may not have another option then doing distributed computing (e.g. with Spark).

Creating an RDD or data frame takes a lot of time, but if you already have data loaded into Spark you should see a good speed-up for large-scale predictions. (I'm closing this as it's not an elephas issue)

**Comment by kuabhish** [comment]
hello @maxpumperla 

What if we want to train on a out of memory data and tune the hyperparameters, Can elephas handle that? If yes , How?
