### ISSUE TITLE
why this error KeyError: Param(parent=u'ElephasEstimator_49f09b9cf514ec3ebc45', name='loss', doc='Keras loss')

### ISSUE THREAD

**Issue by hager123** [maxpumperla/elephas#108]
usr/local/spark/python/pyspark/ml/param/__init__.pyc in getOrDefault(self, param)
    346             return self._paramMap[param]
    347         else:
--> 348             return self._defaultParamMap[param]
    349 
    350     def extractParamMap(self, extra=None):

KeyError: Param(parent=u'ElephasEstimator_49f09b9cf514ec3ebc45', name='loss', doc='Keras loss')

**Comment by abimur-123** [comment]
@hager123 
Do you have your loss set like the command below?
`estimator.set_loss(<your_loss_function>)`

**Comment by danielenricocahall** [comment]
This error occurs if the loss is not set in the `ElephasEstimator`.
