### ISSUE TITLE
Running a single model per node

### ISSUE THREAD

**Issue by yankov** [maxpumperla/elephas#11]
From what I understand it's currently possible to run the same model on multiple workers where each worker gets a different batch of data. But is it possible to run one model per worker where every model may have different parameters but trained on the same batch of data? This could really help for hyperparameter search.

**Comment by maxpumperla** [comment]
Yes, that is actually what I want to achieve next with elephas. Good to see there's interest in that. 

The challenge is exactly the one you mention: how to get different hyperparameters to workers. That is not trivial, as Spark is inherently data-parallel. So my current naive idea is to *reverse* the roles and store model parameters in RDDs (or the like) and broadcast the same set of data to each worker.

Once this is solved, you could even go a step further and use more sophisticated approaches for search on workers (spearmint, hyperopt etc.).

**Comment by yankov** [comment]
Maybe it'd make sense to pass model hyperparameters as json to workers? There is a `to_json` method to turn a model into a json and to turn it back it's just `model.from_json(json_string)`. So the workers start up, load a batch of data (say from s3), then pop jsons from some queue, train the model, store the result, then pop another json from the queue and so on?

**Comment by maxpumperla** [comment]
Thanks, that would make sense. You may have noticed that elephas currently uses yaml serialization, but it doesn't really matter (I wrote the serialization module). S3 sounds great, I was thinking the same. 

If you generate a list of model descriptions on master, you can just parallelize this into an RDD of strings and distribute models to workers with built-in Spark functionality. That's one option.

I like your idea of using a queue. Note that we already have an HTTP parameter server in place, so it would be possible to just extend the requests accordingly, but I'd rather use a system that's specifically built for the task (like Celery). Do you have any suggestions or opinion which MQ to use?

**Comment by maxpumperla** [comment]
Hi @yankov , I've tried to address your use case with this:

https://github.com/maxpumperla/elephas#distributed-hyper-parameter-optimization

Feel free to give me some feedback, if you like.
