### ISSUE TITLE
`predict_classes` in ElephasEstimator

### ISSUE THREAD

**Issue by abishek-murali** [maxpumperla/elephas#111]
I am trying to use the `ElephasEstimator` model as part of my Spark regression pipeline. I notice the `ElephasTransformer` function has [model.predict_classes](https://github.com/maxpumperla/elephas/blob/54e2c161d922886f2cd904cb72ba22fe64b747c3/elephas/ml_model.py#L161) for the Estimator. I have 2 questions based on this:
1. Can the Estimator only be used with Sequential models? (I understand that `predict_classes` is only available for Sequential keras models and not the Model class)
2. Can we only train a classifier using the ElephasEstimator? If yes, is there a method to integrate a regression Elephas model to the Spark pipeline that you would recommend?

**Comment by maxpumperla** [comment]
very good point. that's fairly old code that needs to be revisited. the keras API has changed a lot by now. help is welcome.

**Comment by cdiogo1979** [comment]
Hi
I overloaded the _transform method of the transformer to work with non classification problems
Also the current version of the transform expects a "features" col not takin the info from the estimator config.

def _transform(self, df):
        
        features_col=self.getFeaturesCol()
        
        output_col = self.getOutputCol()

        label_col = self.getLabelCol()
        
        #output_col = "prediction"

        #label_col = "label"

        new_schema = copy.deepcopy(df.schema)

        new_schema.add(StructField(output_col, DoubleType(), True))

        rdd = df.rdd.coalesce(1)

        features = np.asarray(

            #rdd.map(lambda x: from_vector(x.features)).collect())
            rdd.map(lambda x: from_vector(x[features_col])).collect())
    
            # Note that we collect, since executing this on the rdd would require model serialization once again

        #display(len(features[0]))

        model = model_from_yaml(self.get_keras_model_config())

        model.set_weights(self.weights.value)

        #prediction=model.predict(features)
        #display(prediction)

        predictions = rdd.ctx.parallelize(model.predict(features)).coalesce(1)

        #display(predictions.take(2))

        predictions = predictions.map(lambda x: [float(x)])

        #display(predictions.take(2))

        predictions = predictions.map(lambda x: tuple(x))
        
        display(rdd.zip(predictions).take(2))

        results_rdd = rdd.zip(predictions).map(lambda x: x[0] + x[1])

        # TODO: Zipping like this is very likely wrong

        # results_rdd = rdd.zip(predictions).map(lambda pair: Row(features=to_vector(pair[0].features),

        #                                        label=pair[0].label, prediction=float(pair[1])))


        #display(results_rdd.take(2))


        results_df = df.sql_ctx.createDataFrame(results_rdd, new_schema)

        results_df = results_df.withColumn(

            output_col, results_df[output_col].cast(DoubleType()))

        results_df = results_df.withColumn(

            label_col, results_df[label_col].cast(DoubleType()))
        
        return results_df

**Comment by danielenricocahall** [comment]
Both of these problems are resolved in 0.4.5: https://github.com/danielenricocahall/elephas/releases/tag/0.4.5
