### ISSUE TITLE
minimize function (from HyperParamModel) not updated on hyperas 0.4 from elephas?

### ISSUE THREAD

**Issue by anamf** [maxpumperla/elephas#114]
Hi,
I am getting the following error:
`TypeError: minimize() got an unexpected keyword argument 'notebook_name'`

When running the following piece of code:
```
hyperparam_model.minimize(model=model,
                          data=data,
                          max_evals=5,
                          notebook_name='jupyter_sample')
```
These are the versions of elephas and hyperas I use: 
```
! pip freeze | grep hyperas
! pip freeze | grep elephas
hyperas==0.4
elephas==0.3
```
Should I upgrade any of the two?

Thanks,
Ana

**Comment by maxpumperla** [comment]
@anamf please try elephas 0.4, the resp. code is definitely there:

https://github.com/maxpumperla/elephas/blob/master/elephas/hyperparam.py#L33

**Comment by anamf** [comment]
Thanks for your quick response @maxpumperla.
I am running now elephas 0.4. May have I found a typo here (should be trials instead of trails)?:
`trails_list = self.compute_trails(model, data, max_evals, notebook_name)`
Line 39 on:
https://github.com/maxpumperla/elephas/blob/master/elephas/hyperparam.py

**Comment by maxpumperla** [comment]
@anamf thanks for noting this... what a stupid typo. thanks for sending a PR
