### ISSUE TITLE
Faster async SGD

### ISSUE THREAD

**Issue by bhack** [maxpumperla/elephas#12]
What do you think of https://github.com/DoctorTeeth/fred?

**Comment by maxpumperla** [comment]
Thanks, I've seen this before and it surely makes sense to have more elaborate updates on master. Once I finally manage to integrate parallelized hyperparameter calibration and ensemble methods into elephas, this would be a great addition.

However, also note that elephas comes with their own optimizers, i.e. you can send deltas computed with 'pure' SGD from workers and use e.g. Adagrad/delta to aggregate on master. This way you can also address staleness, leading to potentially faster convergence. When it comes to fast as in speed, I think Hogwild is the upper bound.

**Comment by maxpumperla** [comment]
@bhack what's your opinion on it? Would you like to see this in elephas?

**Comment by bhack** [comment]
I still  don't know what is the best schema actually. Other than Yahoo also Amplab it is interfacing Caffe and Tensorflow (that is one of the keras backend). [This is the paper](http://arxiv.org/abs/1511.06051). The repository is at https://github.com/amplab/SparkNet

**Comment by maxpumperla** [comment]
From a methodology perspective, SparkNet actually does less than elephas, as they only have synchronous updates. Same for Yahoo. I wish I could convince Michael Jordan to co-author a piece of software become paper with me. ;)

Spark's syntax invokes some natural constraints, so many approaches look similar. For instance, DL4J has something very similar for Scala as well.

**Comment by bhack** [comment]
For the best schema I meant all recent Async SGD papers. SparkNet is younger but I think that it is important to follow what happens there.

**Comment by maxpumperla** [comment]
Sure, I absolutely agree. Also, if anyone knows how to get the best from Spark, it's Amplab! 

The reason both Amplab and Yahoo don't have asynchronous updates is that it's not easily done with Spark. By that I mean, there's no way to tell Spark to map partitions asynchronously. For this reason, elephas implements a "parameter server" with an HTTP REST API (and Spark just helps with Cluster mgmt and communication / data transport)

To be honest, I think the most flexible framework in terms of schemas, as you say, is Singa right now:
https://singa.incubator.apache.org/

**Comment by nilesh-c** [comment]
@maxpumperla do you think it's worth it to build a deep learning library like Keras purely in Scala and parallelise it with Spark a la ASIP (https://arxiv.org/pdf/1510.07092v1.pdf), using Spark's Akka cluster for async updates? Could it be more reliable and performant? Also, SparkNet's Scala API doesn't look nice at all (it's via javacpp, not idiomatic Scala).

**Comment by maxpumperla** [comment]
@nilesh-c Yes, to be honest I want to to exactly this. The initial problem with building a DL lib in Scala is to pick a good vector library. In my view ND4S is currently the best suited. I have an advanced prototype already, but don't have time to clean it up. Breeze is cool as well, but does not have Tensors. 

In the end, I'm still waiting for the TensorFlow people to start porting core functionality to C++. It's been on the roadmap a long time, but doesn't get started. If this were done, using JavaCpp or swig etc. would give us a Scala version of Tensorflow and I would immediately start migrating and publishing my prototype. 

Are you interested in building something like this yourself?

**Comment by nilesh-c** [comment]
That's brilliant. Yeah, I'd agree on ND4S too, although I'd like it to have sparse arrays soon.

Yes, I'm quite interested in building something like this, but I am looking for a couple of people to collaborate with. :( I'd also like to have model-parallelism (splitting layers or model parameter matrix/tensor among N machines), which, I think, none of the existing Spark-based implementations do (I guess we can get close with a few hacks).

If you already have a prototype with ND4S, maybe we could work on it together?

**Comment by maxpumperla** [comment]
Amazing, I'd love to have somebody on board! But to be clear, I'm not exactly sure if it's worth the effort to continue with ND4S, since I feel that ultimately a lot of DL frameworks _that do not have auto-differentiation_ move very slowly. So, I really want this tensorflow thing to happen. But one could also argue to have a backend abstraction, like keras, and add TF later down the road.

Regarding model-parallelization, it's a bit tricky to do this right, especially since Spark screams for data-parallelism, but I agree that there should be a way.

Let's keep in touch on this one.

**Comment by nilesh-c** [comment]
@maxpumperla Super.

> But to be clear, I'm not exactly sure if it's worth the effort to continue with ND4S, since I feel that ultimately a lot of DL frameworks that do not have auto-differentiation move very slowly.

I agree. I'd be very much for a backend abstraction like keras in pure Scala (maybe we can use pre-existing auto-differentiation libraries in Java/scala if they exist? I'm not sure how to) to keep things flexible and add TF/anything we wish down the road.

What's your email? Mine is nilesh `at` nileshc.com (the blog's down). Let's keep in touch, yeah. Maybe have a couple of skype calls or something and chalk out plans/availabilities.

**Comment by bhack** [comment]
Just an update https://github.com/tensorflow/tensorflow/issues/476#issuecomment-231454081

**Comment by nilesh-c** [comment]
BTW, playing devil's advocate, do we really need a Scala library like that? Apart from being able to do DL with an idiomatic Scala API, does it add any extra value? I mean, how much more performant do we think it'll be over what elephas does (which looks very similar to ASIP I guess, but with http sockets).

**Comment by nilesh-c** [comment]
Related: https://github.com/databricks/tensorframes

**Comment by maxpumperla** [comment]
Good points. In my view it would be more about community, not speed or other technical things. I personally believe Scala will become more important for Data Science as a whole (we need a strongly typed language) and think there's not enough good libraries out there, especially when it comes to DL.

**Comment by maxpumperla** [comment]
@nilesh-c  did you get my mail?

**Comment by agibsonccc** [comment]
Hey all - we are actually starting to work on porting keras to scala that wraps dl4j. We're a big believer in having code written the pythonic way but not having the IPC and interop problems tensorflow with spark or a lot of the other approaches people are taking are. If this is interesting, I'll keep an eye on this thread.

**Comment by bhack** [comment]
We have runned some experiment with Mesos at https://github.com/tensorflow/tensorflow/issues/1996

**Comment by maxpumperla** [comment]
Hey @agibsonccc, sounds great. I'd be definitely interested to hear the latest. If you like, we can further discuss (mail, twitter, etc.). As mentioned, I've dabbled around with my ND4S DL prototype for a while now and would like to further pursue this topic. How would you like to connect?

**Comment by agibsonccc** [comment]
Kick me an email @ adam@skymind.io and we can coordinate.
