### ISSUE TITLE
Discrepancy between release versions

### ISSUE THREAD

**Issue by kalkun** [maxpumperla/elephas#121]
Really cool project! I just wanted to raise a flag on the different release versions between pypy, setup.py and the latest release tagged on github - and I think an issue was the most appropriate way to go.

The version in pypy is 0.3 which is also the latest tagged release on github, however setup.py states version 0.4 on master.

**Comment by maxpumperla** [comment]
https://pypi.org/project/elephas/ have a look, v0.4 was released Nov 16 :)
