### ISSUE TITLE
 ValueError: Improper config format: {'rho': 0.95, 'class_name': 'Adadelta', 'lr': 1.0, 'epsilon': 1e-06}

### ISSUE THREAD

**Issue by maikonabati** [maxpumperla/elephas#122]
Hello!

**After run in Databricks:**
fitted_pipeline = pipeline.fit(train_df)

**Error after execution:**
ValueError: Improper config format: {'rho': 0.95, 'class_name': 'adadelta', 'lr': 1.0, 'epsilon': 1e-06}

**How fix it?**

I try three optimizers: Adadelta, SGD and Adam, my code for Keras Estimator:

> Adadelta = elephas_optimizers.Adadelta()
> estimator = ElephasEstimator()
> estimator.setFeaturesCol("scaled_features")             # These two come directly from pyspark,
> estimator.setLabelCol("index_category")                 # hence the camel case. Sorry :)
> estimator.set_keras_model_config(model.to_yaml())       # Provide serialized Keras model
> estimator.set_optimizer_config(Adadelta.get_config())   # Provide serialized Elephas optimizer
> estimator.set_categorical_labels(True)
> estimator.set_nb_classes(nb_classes)
> estimator.set_num_workers(2)  # We just use one worker here. Feel free to adapt it.
> estimator.set_epochs(20) 
> estimator.set_batch_size(128)
> estimator.set_verbosity(1)
> estimator.set_validation_split(0.15)
> estimator.set_loss('squaredError')

![image](https://user-images.githubusercontent.com/10236346/50286656-37fc9500-0447-11e9-9aa6-2dbed363063f.png)

**Comment by Anirban2404** [comment]
Same error

**Comment by prashant-kikani** [comment]
The issue is, in elephas code itself, they are not returning config in dictionary.
https://github.com/maxpumperla/elephas/blob/master/elephas/optimizers.py#L188

And keras need that.

**Comment by collinpu** [comment]
Same Error, @prashant-kikani Do you have a fix?

**Comment by prashant-kikani** [comment]
Nope.. not solved.. Its library problem.. can't fix until someone send pull request & admin merge it..

**Comment by jovigb** [comment]
optimizer need serialize, like below

from keras import optimizers
adam_conf = optimizers.serialize(optimizers.Adam())
estimator.set_optimizer_config(adam_conf)

**Comment by maxpumperla** [comment]
I removed elephas optimizers altogether in 0.4.2.  You shouldn't see this issue anymore. Let me know.
