### ISSUE TITLE
error on making dl4j docker

### ISSUE THREAD

**Issue by Alireza-cman** [maxpumperla/elephas#123]
Hi, 
I have tried to run a simple code but unfortunately, the code execute a weird procedure. after importing the ``from elephas.ml_model import ElephasEstimator`` it will show the below message: 
 ```pdl4j: required uberjar not found, building with docker...
Docker available. Starting build...
 ```
creating this container take a tremendouse amount of time but after a while it will encounter in 7th step of building docker. 
```
Downloading: http://scala-tools.org/repo-releases/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/nd4j-native-1.0.0-SNAPSHOT-android-arm64.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39:33 min
[INFO] Finished at: 2018-12-29T17:37:28+00:00
[INFO] Final Memory: 20M/64M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pydl4j: Could not resolve dependencies for project org.deeplearning4j:pydl4j:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT, org.nd4j:nd4j-native:jar:android-arm64:1.0.0-SNAPSHOT: Could not find artifact org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT in snapshots-repo (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
based on my search, there isn't such a repository.

**Comment by maxpumperla** [comment]
Those deps are published on Sonatype, see here:

https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/

Do you intend to use the DL4J integration? If yes, maybe try to work with 1.0.0-beta3 and see if that works for you. Snapshots should work too, though... can you reproduce this or was it just the first try?

**Comment by maxpumperla** [comment]
@Alireza-cman

**Comment by maxpumperla** [comment]
p.s.: the wait time is expected, but it's a one-time thing. you need to build all the dl4j jars through pydl4j first.

**Comment by Alireza-cman** [comment]
> 
> 
> Those deps are published on Sonatype, see here:
> 
> https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/
> 
> Do you intend to use the DL4J integration? If yes, maybe try to work with 1.0.0-beta3 and see if that works for you. Snapshots should work too, though... can you reproduce this or was it just the first try?

No I just want to test my Keras code on elephas framework.
yes, I have tested it on my macbook pro three times and our Lab PC (ubuntu 16.04)
I am thinking that ``org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT`` does not exist on the URL indicated on error. check  [(https://oss.sonatype.org/content/repositories/snapshots/)] and the xml file on the bttom of file directory. there is not android-arm in it.

**Comment by Alireza-cman** [comment]
all of a sudden, the pydl4j container is built successfully.

**Comment by maxpumperla** [comment]
yeah, that sometimes happens... snapshot builds can be a little flaky. glad it worked out!
