### ISSUE TITLE
Support of hyperopt space?

### ISSUE THREAD

**Issue by yueguoguo** [maxpumperla/elephas#125]
Does `elephas` support "space" from `hyperopt` for sampling parameter values?

**Comment by yueguoguo** [comment]
I see the discussion [here](https://github.com/hyperopt/hyperopt/issues/414). It would be great to have the feature!

**Comment by maxpumperla** [comment]
yeah, but as you see from that discussion it's not that simple :)

**Comment by yueguoguo** [comment]
@maxpumperla Quite true. Looks like customization of Spark Transformer, Estimator and Evaluator is needed. It is not-trivial though. Will keep an eye on the project. Thanks for the great project. 👍
