### ISSUE TITLE
very low performance

### ISSUE THREAD

**Issue by Alireza-cman** [maxpumperla/elephas#126]
Hi,  
I have tested my model with elephas properly on ``synchronous`` mode. but when I evaluated the model on test data, I got a very low accuracy result. I've changed every parameter that I could change to see a little change on accuracy. however, the accuracy result on test subset was something around 0.17%. 
I was wondering maybe my mode or my parameters could not be compatible for the elephas framework. so I've tested the **mnist_mlp_spark** that is placed in [example](https://github.com/maxpumperla/elephas/tree/master/examples) repo. unfortunately, I've achieved 10 percent of accuracy. is there any problem on my ecosystem ? :/
and another things is that when the mode of fitting is asynchronous, the code will be freezing after the train and does not proceed anymore.

**Comment by cdiogo1979** [comment]
Hi, i would expect that there is something wrong with the Transformer. While training the validation has low loss . After taking the same dataset and doing an prediction + validation the loss is much higher . Another thing i notice is that seems the features are being stored in parquet as int32...

**Comment by maxpumperla** [comment]
@cdiogo1979 thanks for your insights. yeah, how the weights are averaged or otherwise accumulated is an obvious spot to look for. I want to remove elephas optimizers completely for that matter, jfyi

**Comment by AnkBurov** [comment]
Same here. Discovered that after training new trained weights are basically identical with initial weights. Model simply doesn't learn or at least learns new weights, but doesn't save them.

**Comment by maxpumperla** [comment]
@Alireza-cman should be fixed in 0.4.2 - sorry for the inconvenience.
