### ISSUE TITLE
Integrate Keras based model checkpoint based callbacks

### ISSUE THREAD

**Issue by sd12832** [maxpumperla/elephas#130]
https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L360

This would be a nice addition to the distributed framework in order to multiple checkpoints of the weights being trained upon.

**Comment by maxpumperla** [comment]
how does this relate to your other issue, @sd12832 ? Can you please elaborate your idea a little more?

**Comment by sd12832** [comment]
While #131 relates to the class History https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L614 and https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L477, This issue is related to the class ModelCheckpoint Class https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L633. We can integrate both issues into one? Especially since they are both related to bringing in callbacks functionality into Keras.

**Comment by maxpumperla** [comment]
@sd12832 yeah, I'm closing this one. let's discuss in the other. I'll make the title more generic.
