### ISSUE TITLE
parameter server listening port

### ISSUE THREAD

**Issue by alexzhang2010** [maxpumperla/elephas#132]

**Comment by alexzhang2010** [comment]
Is parameter server listening port configurable? I hope it allows to listen on a different port instead of the default port 4000.

**Comment by maxpumperla** [comment]
@alexzhang2010 thanks for the issue. Right now that's hardcoded, but the change required is simple:

https://github.com/maxpumperla/elephas/blob/db8147c501d9ff5dda63931b7c773db999b9743f/elephas/spark_model.py#L71-L72

that's where client and server get initialized, and here is the signature:

https://github.com/maxpumperla/elephas/blob/db8147c501d9ff5dda63931b7c773db999b9743f/elephas/parameter/server.py#L48-L49

So, when initializing a `SparkModel`, we could pass `port` (and other keywords) to it, defaulting to 4000, and pass it into the respective objects.

**Comment by maxpumperla** [comment]
@alexzhang2010 this is now configurable in 0.4.2
