### ISSUE TITLE
problem running elephas_import.py example

### ISSUE THREAD

**Issue by Bfzanchetta** [maxpumperla/elephas#133]
I'm attempting to run /elephas/examples/elephas_import.py on my private cluster.
I set the execution with the command      `sudo spark-submit --driver-memory 10G --conf "spark.pyspark.python=/usr/bin/python2.7" --conf "spark.driver.allowMultipleContexts=true" ./elephas_import.py`      Then it logged:

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.84-1/spark2/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.84-1/spark_llap/spark-llap-assembly-1.0.0.2.6.3.84-1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (org.nd4j.linalg.factory.Nd4jBackend).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using TensorFlow backend.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/02/21 03:12:36 INFO SparkContext: Running Spark version 2.1.0
19/02/21 03:12:38 INFO SecurityManager: Changing view acls to: root
19/02/21 03:12:38 INFO SecurityManager: Changing modify acls to: root
19/02/21 03:12:38 INFO SecurityManager: Changing view acls groups to: 
19/02/21 03:12:38 INFO SecurityManager: Changing modify acls groups to: 
19/02/21 03:12:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/02/21 03:12:38 INFO Utils: Successfully started service 'sparkDriver' on port 45629.
19/02/21 03:12:38 INFO SparkEnv: Registering MapOutputTracker
19/02/21 03:12:38 INFO SparkEnv: Registering BlockManagerMaster
19/02/21 03:12:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/02/21 03:12:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/02/21 03:12:38 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-811c18b8-4b25-4477-8270-9fc01a89313f
19/02/21 03:12:38 INFO MemoryStore: MemoryStore started with capacity 14.5 GB
19/02/21 03:12:38 INFO SparkEnv: Registering OutputCommitCoordinator
19/02/21 03:12:39 INFO Utils: Successfully started service 'SparkUI' on port 4040.
19/02/21 03:12:39 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.0.0.13:4040
19/02/21 03:12:39 INFO Executor: Starting executor ID driver on host localhost
19/02/21 03:12:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37063.
19/02/21 03:12:39 INFO NettyBlockTransferService: Server created on 10.0.0.13:37063
19/02/21 03:12:39 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/02/21 03:12:39 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.0.13, 37063, None)
19/02/21 03:12:39 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.0.13:37063 with 14.5 GB RAM, BlockManagerId(driver, 10.0.0.13, 37063, None)
19/02/21 03:12:39 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.0.13, 37063, None)
19/02/21 03:12:39 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.0.13, 37063, None)
2019-02-21 03:12:40.055931: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
19/02/21 03:12:41 WARN KerasOptimizerUtils: couldn't read momentum parameter
19/02/21 03:12:42 INFO MultiLayerNetwork: Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Traceback (most recent call last):
  File "/home/sshuser/elephas/examples/./elephas_import.py", line 58, in <module>
    main()
  File "/home/sshuser/elephas/examples/./elephas_import.py", line 36, in main
    java_rdd = rdd_utils.to_java_rdd(jsc, x_train, y_train, 32)
  File "/usr/local/lib/python2.7/dist-packages/elephas/utils/rdd_utils.py", line 28, in to_java_rdd
    xi = ndarray(features[:batch_size].copy())
  File "/usr/local/lib/python2.7/dist-packages/elephas/java/ndarray.py", line 262, in __init__
    self.array = _from_numpy(data)
  File "/usr/local/lib/python2.7/dist-packages/elephas/java/ndarray.py", line 113, in _from_numpy
    buff = Nd4j.createBuffer(pointer, size)
  File "jnius/jnius_export_class.pxi", line 900, in jnius.JavaMultipleMethod.__call__
jnius.JavaException: No methods matching your arguments`

What might be the problem?

**Comment by maxpumperla** [comment]
@Bfzanchetta I've been working on a DL4J-backend integration for elephas, to leverage their (much more powerful) parameter servers. Under the hood this uses a tool called `pydl4j` that I wrote, which will build an uberjar with all dependencies and stores it in `~/.deeplearning4j/pydl4j/<context>`.

OK, what your message says is that there is no `createBuffer` method for `Nd4j` with the given signature. The most likely explanations are that either the pydl4j uberjar wasn't properly built, or it uses a dl4j version that's older than what you require. On the machine running your Spark master, can you do

```bash
pydl4j init    # Follow instructions (can confirm defaults)
pydl4j install
```

This should solve the problem. If not I need to go back and investigate / fix the problem upstream in dl4j.

**Comment by Bfzanchetta** [comment]
I did your steps, my setting file config.json is:

`{
"dl4j_core": true, 
"nd4j_backend": "cpu", \
  "spark_version": "2", \
  "datavec": true, \
  "spark": true, \
  "scala_version": "2.11", \
  "dl4j_version": "pydlj install"\
}
`


**My execution log:**

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.84-1/spark2/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.84-1/spark_llap/spark-llap-assembly-1.0.0.2.6.3.84-1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
pdl4j: required uberjar not found, building with docker...
/usr/local/lib/python2.7/dist-packages/pydl4j/pydl4j.py:272: UserWarning: Docker unavailable. Attempting alternate implementation.
  warnings.warn("Docker unavailable. Attempting alternate implementation.")
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:pydl4j:jar:pydlj install
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 201, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pydl4j pydlj install
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/nd4j/nd4j-native-platform/pydlj%20install/nd4j-native-platform-pydlj%20install.pom
[WARNING] The POM for org.nd4j:nd4j-native-platform:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/nd4j/nd4j-native/pydlj%20install/nd4j-native-pydlj%20install.pom
[WARNING] The POM for org.nd4j:nd4j-native:jar:linux-x86_64:pydlj install is missing, no dependency information available
[WARNING] The POM for org.nd4j:nd4j-native:jar:windows-x86_64:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/deeplearning4j/deeplearning4j-core/pydlj%20install/deeplearning4j-core-pydlj%20install.pom
[WARNING] The POM for org.deeplearning4j:deeplearning4j-core:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/deeplearning4j/dl4j-spark-parameterserver_2.11/pydlj%20install_spark_2/dl4j-spark-parameterserver_2.11-pydlj%20install_spark_2.pom
[WARNING] The POM for org.deeplearning4j:dl4j-spark-parameterserver_2.11:jar:pydlj install_spark_2 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-api/pydlj%20install/datavec-api-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-api:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-local/pydlj%20install/datavec-local-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-local:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-arrow/pydlj%20install/datavec-arrow-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-arrow:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-camel/pydlj%20install/datavec-camel-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-camel:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-excel/pydlj%20install/datavec-excel-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-excel:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-geo/pydlj%20install/datavec-geo-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-geo:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-hadoop/pydlj%20install/datavec-hadoop-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-hadoop:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-jdbc/pydlj%20install/datavec-jdbc-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-jdbc:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-perf/pydlj%20install/datavec-perf-pydlj%20install.pom
[WARNING] The POM for org.datavec:datavec-perf:jar:pydlj install is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-spark_2.11/pydlj%20install_spark_2/datavec-spark_2.11-pydlj%20install_spark_2.pom
[WARNING] The POM for org.datavec:datavec-spark_2.11:jar:pydlj install_spark_2 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/bytedeco/javacpp/1.4.2/javacpp-1.4.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/nd4j/nd4j-native-platform/pydlj%20install/nd4j-native-platform-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/nd4j/nd4j-native/pydlj%20install/nd4j-native-pydlj%20install-linux-x86_64.jar
Downloading: https://repo.maven.apache.org/maven2/org/nd4j/nd4j-native/pydlj%20install/nd4j-native-pydlj%20install-windows-x86_64.jar
Downloading: https://repo.maven.apache.org/maven2/org/deeplearning4j/deeplearning4j-core/pydlj%20install/deeplearning4j-core-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/deeplearning4j/dl4j-spark-parameterserver_2.11/pydlj%20install_spark_2/dl4j-spark-parameterserver_2.11-pydlj%20install_spark_2.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-api/pydlj%20install/datavec-api-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-local/pydlj%20install/datavec-local-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-arrow/pydlj%20install/datavec-arrow-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-camel/pydlj%20install/datavec-camel-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-excel/pydlj%20install/datavec-excel-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-geo/pydlj%20install/datavec-geo-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-hadoop/pydlj%20install/datavec-hadoop-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-jdbc/pydlj%20install/datavec-jdbc-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-perf/pydlj%20install/datavec-perf-pydlj%20install.jar
Downloading: https://repo.maven.apache.org/maven2/org/datavec/datavec-spark_2.11/pydlj%20install_spark_2/datavec-spark_2.11-pydlj%20install_spark_2.jar
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
Downloaded: https://repo.maven.apache.org/maven2/org/bytedeco/javacpp/1.4.2/javacpp-1.4.2.jar (352 KB at 204.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar (41 KB at 18.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.736 s
[INFO] Finished at: 2019-02-21T17:00:48+00:00
[INFO] Final Memory: 19M/1273M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pydl4j: Could not resolve dependencies for project org.deeplearning4j:pydl4j:jar:pydlj install: The following artifacts could not be resolved: org.nd4j:nd4j-native-platform:jar:pydlj install, org.nd4j:nd4j-native:jar:linux-x86_64:pydlj install, org.nd4j:nd4j-native:jar:windows-x86_64:pydlj install, org.deeplearning4j:deeplearning4j-core:jar:pydlj install, org.deeplearning4j:dl4j-spark-parameterserver_2.11:jar:pydlj install_spark_2, org.datavec:datavec-api:jar:pydlj install, org.datavec:datavec-local:jar:pydlj install, org.datavec:datavec-arrow:jar:pydlj install, org.datavec:datavec-camel:jar:pydlj install, org.datavec:datavec-excel:jar:pydlj install, org.datavec:datavec-geo:jar:pydlj install, org.datavec:datavec-hadoop:jar:pydlj install, org.datavec:datavec-jdbc:jar:pydlj install, org.datavec:datavec-perf:jar:pydlj install, org.datavec:datavec-spark_2.11:jar:pydlj install_spark_2: Could not find artifact org.nd4j:nd4j-native-platform:jar:pydlj install in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Traceback (most recent call last):
  File "/home/sshuser/elephas/examples/./elephas_import.py", line 1, in <module>
    from elephas.java import java_classes
  File "/usr/local/lib/python2.7/dist-packages/elephas/java/java_classes.py", line 4, in <module>
    pydl4j.validate_jars()
  File "/usr/local/lib/python2.7/dist-packages/pydl4j/pydl4j.py", line 302, in validate_jars
    maven_build()
  File "/usr/local/lib/python2.7/dist-packages/pydl4j/pydl4j.py", line 273, in maven_build
    _maven_build(use_docker=False)
  File "/usr/local/lib/python2.7/dist-packages/pydl4j/pydl4j.py", line 264, in _maven_build
    os.rename(source, target)
OSError: [Errno 2] No such file or directory
`
I will keep looking on this, thanks for the help!
