### ISSUE TITLE
Probabilities using elephas ?

### ISSUE THREAD

**Issue by irfaanmeah** [maxpumperla/elephas#137]
Do we get probabilities out using elephas ? I do not see an option in the examples provided.

**Comment by danielenricocahall** [comment]
@irfaanmeah Can you clarify what you mean by probabilities?

**Comment by danielenricocahall** [comment]
This is now supported with 1.4.1 release. Please test it out and let me know what you think! Just need to `set_predict_classes` to `False` in the estimator.
