### ISSUE TITLE
 what is the *data parallel* meaning here? 

### ISSUE THREAD

**Issue by fluency03** [maxpumperla/elephas#14]
There are some data parallel exmaples: [here](https://github.com/maxpumperla/elephas/blob/master/examples/mnist_mlp_spark.py) and [here](https://github.com/maxpumperla/elephas/blob/master/examples/mllib_mlp.py) 

I am wondering what is the *data parallel* meaning here? 

Does it mean that: during each of the epoch, the many batches are paralleled and trained on different workers? After one worker finished its job on one batch, it will update the model weights?   

That means, master parallel the batches into different workers right? The total training is still based on the train data set, not partial of the training data set.

**Comment by fluency03** [comment]
Do you have any idea about the speed-up with such data parallel?   For example, a cpu-cluster with 10 nodes compared with Amazon g2.2xlarge instance?

**Comment by maxpumperla** [comment]
It's data-parallel as in https://en.wikipedia.org/wiki/Data_parallelism, i.e. if you have n workers, then each of them receives roughly num_samples/n samples. I can also recommend the wiki of Spark for what RDDs exactly do internally.

As for the speed-up, that depends heavily on your setup. There's a certain trade-off between network bandwidth and parallelisation speed-up. For instance, if your model is *huge*, it might take very long for it to be serialized and sent to workers. 

You can parallelize on g2.2xlarge instances as well. They have 4 gpus, each usually run 10-100 times faster on convnets than CPUs.. So, such a setup would easily crush 10 CPUs. Also, the less you parallelize, the more data each worker receives. All in all, we've achieved some good results on g2.2xlarge instances.

**Comment by fluency03** [comment]
Do you mean that, normally, if I run the Keras model on g2.2xlarge, it will only use one GPU instead of all of the four GPUs?   

Can I easily use all of them by just doing some configurations on Keras or Theano withouting implementing elephas or spark?

**Comment by maxpumperla** [comment]
Spark workers run on one machine (physical or virtual). For multi-gpu setup on one machine for keras, you can google for theano or tensorflow multi-gpu:

https://github.com/Theano/Theano/wiki/Using-Multiple-GPUs
https://www.tensorflow.org/versions/r0.7/how_tos/using_gpu/index.html

If you know how to do that you can combine with elephas, i.e. use multi-gpu on each worker

**Comment by maxpumperla** [comment]
Though I really like to discuss such things, usually github issues are meant for actual issues. Would you agree to close this one?

**Comment by pengpaiSH** [comment]
@maxpumperla Hi Max, I have a basic question here. I am using Keras with TensorFlow as backend. And I really wanna to do the data parallelism during my training, i.e. faster convergence with larger batch size. Can elephas help me meet this demand?
