### ISSUE TITLE
Log output overwhelming

### ISSUE THREAD

**Issue by michaelmior** [maxpumperla/elephas#140]
When I train my model with Elephas, my console is flooded with messages like those below making it nearly impossible to monitor progress. How can I disable these?

```
127.0.0.1 - - [08/May/2019 14:21:45] "GET /parameters HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2019 14:21:45] "POST /update HTTP/1.1" 200 -
```

**Comment by maxpumperla** [comment]
I think you can turn this off with `debug=False` in the underlying flask application here:

https://github.com/maxpumperla/elephas/blob/master/elephas/parameter/server.py#L48

unfortunately, I don't currently pass this through as parameter in Elephas models, but you can modify the call here:

https://github.com/maxpumperla/elephas/blob/master/elephas/spark_model.py#L69

hope this helps. If you find a good log level, please just send a PR. I'm not sure I want to keep these messages in there either. thanks!
