### ISSUE TITLE
Elephas, Keras model (not sequential), multiple input vectors - get predictions?

### ISSUE THREAD

**Issue by GeoffDuniam** [maxpumperla/elephas#145]
Hi everyone,
 We have a recurrent neural network model that we've been able to implement in Elephas. The feature vector with the shape (, 2314) contains three inputs, namely a vector of (?,10) of metadata, a bandwidth vector of (?, 256) and the features vector of (?,2048) that gets reshaped into (,256,8). (This is a workaround to address https://github.com/maxpumperla/elephas/issues/16)

Here's the model (it's an Elephas implementation of a detection problem for a Light curve kaggle competition, see https://www.kaggle.com/zerrxy/plasticc-rnn)

    def get_model(train_df, input_dim, size=80):

    def get_meta(x):
        x=x[:,0:10]
        return x
    
    def get_band(x):
        x=x[:,10:266]
        return x
    
    def get_hist(x):
        x=x[:,266:input_dim]
        x=Reshape((8,256))(x)
        x=K.permute_dimensions(x, (0,2,1))
        return x

    
    raw_input  = Input(shape=train_df.select("features").first()[0].shape, name='raw')
    
    hist_input = Lambda(get_hist,  name="hist")(raw_input)
    meta_input = Lambda(get_meta,  name="meta")(raw_input)
    band_input = Lambda(get_band,  name="band")(raw_input)
    
    band_emb = Embedding(8, 8)(band_input)
    hist = concatenate([hist_input, band_emb])
    hist = TimeDistributed(Dense(40, activation='relu'))(hist)
    
    rnn = Bidirectional(GRU(size, return_sequences=True))(hist)
    rnn = SpatialDropout1D(0.5)(rnn)
    
    gmp = GlobalMaxPool1D()(rnn)
    gmp = Dropout(0.5)(gmp)
    
    x = concatenate([meta_input, gmp])
    x = Dense(128, activation='relu')(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    
    output = Dense(15, activation='softmax')(x)
    model = Model(inputs=[raw_input], outputs=output)
    
    return model

Here's the model summary

[ModelSummary.txt](https://github.com/maxpumperla/elephas/files/3710367/ModelSummary.txt)

To run it all, we set up a pipeline (for this example, haven't bothered with a standard scaler, etc)

pipeline = Pipeline(stages=[estimator])
fitted_pipeline = pipeline.fit(train_df)

Runs fine, apparently -
>>> Fit model
>>> Synchronous training complete.
Model trained in 340.7032928466797 seconds

The problems start when we want to run predictions, because the Model class has no attribute "predict_classes",  see

prediction = fitted_pipeline.transform(train_df)
...
AttributeError: 'Model' object has no attribute 'predict_classes'

So, for the model class, we need to utilise the "predict" attribute. However, the ElephasTransformer has no predict attribute, either - if we isolate the ElephasTransformer from the pipeline

fitted_pipeline.stages
[ElephasTransformer_472084d5fe78b0bfa915]

fitted_pipeline.stages[-1].predict(train_df)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-7a84f512107d> in <module>
----> 1 fitted_pipeline.stages[-1].predict(train_df)

AttributeError: 'ElephasTransformer' object has no attribute 'predict'

So - we can create a Model class and train it using Elephas, but if we're using Model rather than Sequential, any suggestions on how to transform and get predictions?

**Comment by kris1710** [comment]
Facing the same issue, Did you find any workaround this?

**Comment by GeoffDuniam** [comment]
Hi kris1710,

We have a very rough workaround (and I do mean very rough) that may work - still playing around with it to clean it up. It's an implementation of #111 and it will run - but the output is a little inconsistent. I've had to put the investigation into this on hold (trying to get a paper submitted for review before the end of next week). Basically, it's a modification of the ml_model.py library to include a predict attribute, I can't guarantee it's fit for purpose or it's accuracy or even if the logic is sound, but the changes we made are detailed here,

[ml_model.txt](https://github.com/maxpumperla/elephas/files/3850066/ml_model.txt)

Have a look and see what you think. Again, let me stress that this is rough. If you find a way to get it cleaned up and working, let me know!

Cheers

Geoff

**Comment by maxpumperla** [comment]
@GeoffDuniam if you could get this onto a remote branch of a fork of elephas or so, it'd be much easier for me to review and distill your ideas into something that could become a fix.

Thanks for looking into this btw.

**Comment by GeoffDuniam** [comment]
@maxpumperla  Hi Max, will do as soon as I can - like I said, it's extremely rough and  certainly needs work.  Got it working on Keras Model classes with n-dimensional feature vectors, but getting the predict class working was a little complex - the use case we're looking at has custom loss functions that I suspect we'll to be able to pass in at some stage.

Could be a couple of weeks before I can revisit this, currently I'm working on getting a paper for describing data modelling techniques for light curve data on Keras Neural Networks ready for pulication and that's taking up most of my time at present. I'll get back to it as soon as I can and let you know.

Cheers

Geoff

**Comment by maxpumperla** [comment]
no worries and thanks again. rough is perfectly OK, I'm glad somebody found the time to look at this at all!

**Comment by danielenricocahall** [comment]
As of 0.4.5, there is support for the Keras functional API, so this should no longer be an issue. Regarding multiple inputs, that's a separate issue which I will be looking into for a future release.
