### ISSUE TITLE
Column mismatch when doing fitted_model.transform(data)

### ISSUE THREAD

**Issue by zanderkent** [maxpumperla/elephas#155]
![image](https://user-images.githubusercontent.com/20103229/74687626-2a998280-5192-11ea-838b-6c706b5cb463.png)
![image](https://user-images.githubusercontent.com/20103229/74687788-a7c4f780-5192-11ea-9ed0-00ac8a547a00.png)

As you can see the training works fine, but when I try to predict on the same dataframe it is expecting 5 columns, instead of the 3 columns that it has. I've done some serious googling and I cannot find the answer :(

![image](https://user-images.githubusercontent.com/20103229/74687708-603e6b80-5192-11ea-80da-e9ceb989ea2c.png)

Here is the full stack trace (Bolded the actual issue)
`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-69-81503cf684ab> in <module>()
      1 pnl = predictions.select("label", "prediction")
----> 2 pnl.show(100)

/opt/mapr/spark/spark/python/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
    348         """
    349         if isinstance(truncate, bool) and truncate:
--> 350             print(self._jdf.showString(n, 20, vertical))
    351         else:
    352             print(self._jdf.showString(n, int(truncate), vertical))

/opt/mapr/spark/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/mapr/spark/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/mapr/spark/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1682.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 54.0 failed 4 times, most recent failure: Lost task 0.3 in stage 54.0 (TID 2199, lgpbd5222.gso.aexp.com, executor 56): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/tmp/hadoop-mapr/nm-local-dir/usercache/ajkent/appcache/application_1581551187721_322146/container_e248_1581551187721_322146_01_003773/pyspark.zip/pyspark/worker.py", line 253, in main
    process()
  File "/tmp/hadoop-mapr/nm-local-dir/usercache/ajkent/appcache/application_1581551187721_322146/container_e248_1581551187721_322146_01_003773/pyspark.zip/pyspark/worker.py", line 248, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/tmp/hadoop-mapr/nm-local-dir/usercache/ajkent/appcache/application_1581551187721_322146/container_e248_1581551187721_322146_01_003773/pyspark.zip/pyspark/serializers.py", line 379, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/tmp/hadoop-mapr/nm-local-dir/usercache/ajkent/appcache/application_1581551187721_322146/container_e248_1581551187721_322146_01_003773/pyspark.zip/pyspark/util.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/opt/mapr/spark/spark/python/pyspark/sql/session.py", line 679, in prepare
    verify_func(obj)
  File "/opt/mapr/spark/spark/python/pyspark/sql/types.py", line 1421, in verify
    verify_value(obj)
  File "/opt/mapr/spark/spark/python/pyspark/sql/types.py", line 1400, in verify_struct
    "length of fields (%d)" % (len(obj), len(verifiers))))
**ValueError: Length of object (5) does not match with length of fields (3)`**

**Comment by AntonOellerer** [comment]
Hey, I had a similar problem and fixed this by passing `elephas_estimator.set_optimizer_config` a `SGD` optimizer instead of an `Adam` optimizer.

**Comment by leozzz620** [comment]
> Hey, I had a similar problem and fixed this by passing `elephas_estimator.set_optimizer_config` a `SGD` optimizer instead of an `Adam` optimizer.

Hi, I have used your method, but it doesn't fixed. Can you tell me more about how to fix it?

**Comment by AntonOellerer** [comment]
Thats all I did, here is the code excerpt if it helps you:
```Python
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers import LeakyReLU
from keras.optimizers import SGD, Adam
from keras import optimizers
from elephas.ml_model import ElephasEstimator

model = Sequential()
model.add(Dense(128, input_dim=transformed_train_sample.head()['features'].size))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(64))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(32))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(16))
model.add(Activation('sigmoid'))
adam = optimizers.Adam(lr = 0.00001)
model.compile(loss='mean_squared_error', optimizer=adam)

sgd = optimizers.SGD(lr=0.01)

opt_conf = optimizers.serialize(sgd)

estimator = ElephasEstimator()
estimator.set_keras_model_config(model.to_yaml())
estimator.set_batch_size(32)
estimator.set_frequency('batch')
estimator.set_categorical_labels(True)
estimator.set_nb_classes(16)
estimator.setLabelCol("label_index")
estimator.setFeaturesCol("features")
estimator.setOutputCol("predictions")
estimator.set_loss('mean_squared_error')
estimator.set_optimizer_config(opt_conf)

estimator_pipeline = Pipeline(stages=[estimator])
estimator_model = estimator_pipeline.fit(transformed_train_sample)
#estimator_model.save("estimator_model")

eval_predictions = estimator_model.transform(transformed_eval_sample)
```

**Comment by danielenricocahall** [comment]
This was actually an issue with not supporting regression problems. Regression problems are officially supported as of 0.4.5!
