### ISSUE TITLE
AttributeError: 'ElephasEstimator' object has no attribute 'setFeaturesCol'

### ISSUE THREAD

**Issue by Binjielu** [maxpumperla/elephas#157]
When I was initializing ElephasEstimator, I can't set features col nor label index? Can anyone help?

**Comment by Soothysay** [comment]
Can you share your code snippet?

**Comment by gprashmi** [comment]
Hi, 

Even I am facing the same issue. Below is my code:

#my initial spark statements
     from pyspark import SparkContext, SparkConf
     from pyspark.sql import SQLContext
     conf = SparkConf().setAppName('Elephas_App').setMaster('local[4]')
     sc = SparkContext(conf=conf)
     sql_context = SQLContext(sc)
     #SQLcontext is created using sc for realational functionality
     sql_context = SQLContext(sc)

    #elephas estimator parameters
    optimizer_conf = optimizers.Adam(lr = 0.01)
    opt_conf = optimizers.serialize(optimizer_conf)

    estimator = ElephasEstimator()
    estimator.set_keras_model_config(model.to_yaml())
    estimator.set_categorical_labels(True)
    estimator.set_nb_classes(tar_class)
    estimator.set_num_workers(1)
    estimator.set_epochs(5)
    estimator.set_batch_size(64)
    estimator.setFeaturesCol("features")
    estimator.setLabelCol("label")
    estimator.set_verbosity(1)
    estimator.set_validation_split(0.10)
    estimator.set_optimizer_config(opt_conf)
    estimator.set_mode("synchronous")
    estimator.set_loss("binary_crossentrophy")
    estimator.set_metrics(["acc"])

I am facing with the following issue:

    AttributeError                            Traceback (most recent call last)
    <ipython-input-92-74397f47b924> in <module>()
           7 estimator.set_epochs(5)
           8 estimator.set_batch_size(64)
           ----> 9 estimator.setFeaturesCol("features")
           10 estimator.setLabelCol("label")
           11 estimator.set_verbosity(1)

     AttributeError: 'ElephasEstimator' object has no attribute 'setFeaturesCol'

This issue exists for both "setFeaturesCol" and "setLabelCol". 
Can anyone please help me as I am new to this? Thanks in advance!

**Comment by gprashmi** [comment]
@Binjielu I resolved this issue by just removing the two lines:

estimator.setFeaturesCol("features")
estimator.setLabelCol("label")

Since we define the input and output through our model, it code works fine without these lines.

**Comment by mawfia** [comment]
Apologize if too late but for anyone using PySPark API 3.0+ that reads this in the future you can set the feature and label columns in the ElephasEstimator constructor as such:

estimator = ElephasEstimator(labelCol='label', featuresCol='feature')

You can set all or a combination of the attributes in the constructor by omitting 'set' and 'set_' and use lowercase for first letter.

**Comment by danielenricocahall** [comment]
Thank you @mawfia ! I may add a deprecation warning to these methods to avoid this issue in the future.
