### ISSUE TITLE
TypeError: get_hyperopt_model_string() missing 1 required positional argument: 'data_args'

### ISSUE THREAD

**Issue by M-A-A-B** [maxpumperla/elephas#160]
I am trying use minimize function of HyperParamModel like mentioned below:
```
hyperparam_model.minimize(model=model,
                          data=data,
                          max_evals=5)
```
And I am getting the following error:
`TypeError: get_hyperopt_model_string() missing 1 required positional argument: 'data_args'`

I think this issue is related to the following resolved issues:
[https://github.com/maxpumperla/elephas/issues/79](url)
[https://github.com/maxpumperla/elephas/issues/35](url)

The error is given on the following piece of code from hyperparam.py file of Elephas:

```
def compute_trials(self, model, data, max_evals, notebook_name):
        model_string = get_hyperopt_model_string(model=model, data=data, functions=None, notebook_name=notebook_name,
                                                 verbose=False, stack=3)
        hyperas_worker = HyperasWorker(model_string, max_evals)
        dummy_rdd = self.spark_context.parallelize([i for i in range(1, 1000)])
        dummy_rdd = dummy_rdd.repartition(self.num_workers)
        trials_list = dummy_rdd.mapPartitions(
            hyperas_worker._minimize).collect()

        return trials_list
```

Probably the function call for get_hyperopt_model_string() needs to be updated with 'data_args' as an argument.
Can we please get this resolved?
Thank you.

**Comment by danielenricocahall** [comment]
Is this still an issue?
