### ISSUE TITLE
Use elephas to do multi-label classification

### ISSUE THREAD

**Issue by SaiBeathanabhotla** [maxpumperla/elephas#162]
I came across Elephas to distribute Keras models in Spark. I am using it for multi-class classification problem and it seems to work fine.

I am wondering how to use this for multi-label classification where the target variable will be a list of 0's and 1's. For example, the target variable can be [0, 0, 1, 0 ,1 0, 0 , 0 , 1, 1]. I have the Keras model which works on a pandas dataframe for multi-label classification problem. So I wanted to try it on Spark Dataframe and not able to make it work.

Can you please help me with this? Thanks in advance.

**Comment by SaiBeathanabhotla** [comment]
Can someone please help me with this?

**Comment by danielenricocahall** [comment]
Hello @SaiBeathanabhotla, what was the primary issue with doing multi-label classification? Was the model just performing poorly, or was there an actual error?

**Comment by danielenricocahall** [comment]
This may be related - in https://github.com/maxpumperla/elephas/pull/177, we introduce the capability of predicting probabilities in the `ElephasTransformer`. Between this feature and the `predict` method on the `SparkModel`, I believe that functionally, multi-class classification should be feasible - the only issue is that predicting the classes has to happen on the application side, since the output in both cases is an array of "probabilities".

**Comment by SaiBeathanabhotla** [comment]
It was an actual error. Since the target variable is multi-label (array) but Elephas was expecting a float. So I was getting an error of type mismatch.
Also, as you mentioned you have introduced the capability of predicting probabilities, I would want to try it out. Do you have a working notebook that I can try out?

**Comment by danielenricocahall** [comment]
It should be in the next release, which will be coming out later tonight or early tomorrow.

**Comment by danielenricocahall** [comment]
This is offically in 1.4.1 release - please try it out at earliest convenience!

**Comment by danielenricocahall** [comment]
@SaiBeathanabhotla have you gotten a chance to test the feature out?

**Comment by danielenricocahall** [comment]
I'm going to close this out for now. Feel free to reopen this ticket or open a new one if the latest version  (3.0.0) doesn't work!
