### ISSUE TITLE
[ElephasTransformer] inefficient transform method?

### ISSUE THREAD

**Issue by OscarDPan** [maxpumperla/elephas#172]
Hi if I understand correctly, the ElephasTransformer does not do distributed inference instead it first collects all rdds to the driver and let driver does the prediction before parallelizing it to the spark cluster.

https://github.com/maxpumperla/elephas/blob/master/elephas/ml_model.py#L185

Isn't this approach quite inefficient? Why not use something like dataframe udf to do the inference? 

I'd love to help with that if you think my suggestion is correct.

**Comment by danielenricocahall** [comment]
@OscarDPan good point! I actually reviewed and refactored it myself - we now perform feature extraction + inference in a distributed way. I will make a minor release for this update.

**Comment by OscarDPan** [comment]
awesome! Looking forward to it

**Comment by danielenricocahall** [comment]
Test it out in 1.3.1!

**Comment by OscarDPan** [comment]
Hi @danielenricocahall Thanks for the quick update and release!
I read your commit and thought it's reasonable but when I tried it out on a small dataset the speed was surprisingly significantly slower than the old way.
I am going to try other ways of implementation and see if I can speed it up. Will keep you posted :)

**Comment by OscarDPan** [comment]
Hi @danielenricocahall 
So I've been using pyspark's SparseVector to represent my features
and in my case if I use
```
return predict_function(np.array([x[features_col].toArray() for x in data]))
```
it will give me a very good performance boost.

**Comment by danielenricocahall** [comment]
Closed with https://github.com/maxpumperla/elephas/pull/176
