### ISSUE TITLE
Synchronization mode update logic

### ISSUE THREAD

**Issue by OscarDPan** [maxpumperla/elephas#173]
Hi @danielenricocahall 
I saw another possible bug in the model synchronization logic
https://github.com/maxpumperla/elephas/blob/master/elephas/spark_model.py#L184

Let's say we train 2 models on separate datasets and in the end we update the master network. If we take average of the models we then have ((initial_weights + delta_1) + (initial_weights + delta_2)) / 2 == initial_weights + delta_1 / 2 + delta_2 / 2

I am not convinced that updating the master network with the un-weighted deltas is the right way. Think about what if both models are at the optimal point after the updates delta_1 and delta_2, respectively. Then the master network is "over" updated.

Here are my 2 suggestions:
1. Divide the deltas by number of rdd partitions
2. We actually don't need to remember the deltas at all, we can just return final_weights/num_rdd_partitions and update the master network by the weighted sum of the worker networks - Doing this we can optimize memory.

I really appreciate your effort to keep this project alive! Again if you need help I'd love to :)

**Comment by danielenricocahall** [comment]
Closed with https://github.com/maxpumperla/elephas/pull/176
