### ISSUE TITLE
options to predict probabilities given a classification model

### ISSUE THREAD

**Issue by OscarDPan** [maxpumperla/elephas#174]
Can we make it optional to predict either a label or probability when 
```
model_type == ModelType.CLASSIFICATION
```
There are a lot of use case in the industry that probability prediction is more important than just label prediction.

Thanks.

**Comment by danielenricocahall** [comment]
Good suggestion! I can work on that, or feel free to add it yourself in a PR :) . I think it should be fairly simple.

**Comment by danielenricocahall** [comment]
@OscarDPan feel free to take a look at https://github.com/maxpumperla/elephas/pull/177. If you think it's good, I'll merge it in.

**Comment by OscarDPan** [comment]
hey @danielenricocahall Thanks for the quick update! Generally LGTM and I left a comment.

**Comment by danielenricocahall** [comment]
@OscarDPan I don't see the comment - is the review submitted?

**Comment by danielenricocahall** [comment]
Done and released in 1.4.1!
