### ISSUE TITLE
Elephas compatibility with tensorflow > 2.2

### ISSUE THREAD

**Issue by bdikici** [maxpumperla/elephas#185]
Hey guys,

I love what you guys are doing with this project, keep it up <3. I was just wondering if there are any talks about releasing a version which is compatible with the Tensorflow versions > 2.2.

Greetings and stay safe

**Comment by danielenricocahall** [comment]
Hi @bdikici ! Thank you! IIRC, Elephas was compatible with 2.3 when testing locally, just 2.2.x had some issues. I may pin it to >=2.3 soon.

**Comment by danielenricocahall** [comment]
Okay, support for higher TF versions is officially merged into master: https://github.com/maxpumperla/elephas/pull/186. Once the next release (2.0.0) is out, I will close this issue. Feel free to test it out and let me know how it works!

**Comment by danielenricocahall** [comment]
Officially released Elephas 2.0.0 which has > 2.2 support. Please feel free to test it out!
