### ISSUE TITLE
 [BUG] ml_model _transform 

### ISSUE THREAD

**Issue by OscarDPan** [maxpumperla/elephas#187]
Hey @danielenricocahall I've been lately trouble shooting a pretty bizarre issue but haven't been able to find the root cause yet. I want to share with you my progress.
1. This issue is independent from my existing PR.
2. This issue is only observed in spark **CLUSTER** mode. 

The problem is my elephas model works as expected in local spark mode, but in cluster mode after it does predictions, the output is a total mess as if the input rdd and predictions rdd is out of order.

I have confirmed that up to what happens inside this block
```
predictions = rdd.mapPartitions(
            partial(extract_features_and_predict,
            ...))
```
everything is still correct. i.e. I added code to calculate metrics inside the mapPartitions and the metric makes sense

However, if I calculate the metrics again using the output of the _transform() func, the metrics don't make sense any more.

**Comment by OscarDPan** [comment]
So I still am don't understand why this only happens in cluster mode, but if I persisit the df before it goes to _transform, everything is good!

**Comment by danielenricocahall** [comment]
@OscarDPan can you send a minimal reproducible example?

**Comment by OscarDPan** [comment]
@danielenricocahall as I mentioned the issue was never discovered during local development/unittests. It is only observed when I run my end-to-end code in a cluster.

But what I understand is if the input df to the _transform() func was previously shuffled (e.g. repartition, orderBy), we cannot guarantee the 2 rdds in `rdd.zip(prediction_rdd)` have the same order, because the input df was actually materialized twice (one inside the mapPartition and the other when users try to materialize the output of the _tranform() func.)

It makes sense to me that I should persist the input df such that the row orders are preserved, but I am still perplexed as to why it's neven happend in local spark model.

**Comment by danielenricocahall** [comment]
@OscarDPan ah okay - we could also introduce an `id` column prior to inference and add a sort prior to the return to ensure the ordering.

**Comment by OscarDPan** [comment]
@danielenricocahall  yeah that's also a solution :) Ideally an optional argument. In my case I'd use persist over sort since my dataset has millions of rows.
