### ISSUE TITLE
Elephas in Mesos

### ISSUE THREAD

**Issue by bhack** [maxpumperla/elephas#19]
@maxpumperla we are also experimenting elephas in mesos. Do you have tried to submit at the Spark Mesos dispatcher, so in deploy-mode cluster using docker containers?

**Comment by bhack** [comment]
I.e. It could be really helpful for users to publish a elephas dockerfile on dockerhub. There are already some official or semiofficial dockerfile for tensorflow, spark, theano etc. So a good ready to run dockerfile for elepahs to deploy and scale on mesos would really appealing.

**Comment by misi1987107** [comment]
Hey man, Did you try use elephas in yarn?Does that work?
