### ISSUE TITLE
Does support LSTM or GRU models?

### ISSUE THREAD

**Issue by ghorbani-mohammad** [maxpumperla/elephas#190]
Hi,

Does this package support LSTM or GRU models for training on spark?

Thanks for your great work :)

**Comment by danielenricocahall** [comment]
Thank you! Not exactly - there are several other open issues (https://github.com/maxpumperla/elephas/issues/141, https://github.com/maxpumperla/elephas/issues/85) regarding LSTM support. It's something I could add but I would definitely need some help.

**Comment by paravatha** [comment]
Hi, was LSTM and Bidirectional LSTM added in the recent release?

**Comment by danielenricocahall** [comment]
Hi @paravatha it was not - that's still an ongoing effort. Feel free to start it and we can work on it together if you have any ideas!

**Comment by rebelobru** [comment]
Hello!
Was LSTM added in the meantime?
I tried to use a LSTM layer and fit it with a rdd and it did run without any error. Do you think that it was a case of luck and the results might be correct?

**Comment by danielenricocahall** [comment]
Hello @rebelobru! LSTM wasn't added - it may work in the sense that a model will train, but I haven't thought through if it would actually work in the current paradigm. Out of curiosity, how did the results look in the LSTM model trained with elephas?

**Comment by danielenricocahall** [comment]
Moved this issue to the new fork: https://github.com/danielenricocahall/elephas/issues/10. Closing this for now but still on the radar!
