### ISSUE TITLE
RuntimeError: Method `model.to_yaml()` has been removed due to security risk of arbitrary code execution. Please use `model.to_json()` instead.

### ISSUE THREAD

**Issue by aabbcc002** [maxpumperla/elephas#194]
After Tensorflow 2.4.3, the error "RuntimeError: Method `model.to_yaml()` has been removed due to security risk of arbitrary code execution. Please use `model.to_json()` instead." is broken.

message:
RuntimeError                              Traceback (most recent call last)
<ipython-input-86-5447e921f37e> in <module>
      1 from elephas.spark_model import SparkModel
      2 spark_model = SparkModel(model, frequency='epoch', mode='asynchronous')
----> 3 spark_model.fit(rdd, epochs=20, batch_size=32, verbose=0, validation_split=0.1)

~/.pyenv/versions/3.6.13/lib/python3.6/site-packages/elephas/spark_model.py in fit(self, rdd, **kwargs)
    148 
    149         if self.mode in ['asynchronous', 'synchronous', 'hogwild']:
--> 150             self._fit(rdd, **kwargs)
    151         else:
    152             raise ValueError(

~/.pyenv/versions/3.6.13/lib/python3.6/site-packages/elephas/spark_model.py in _fit(self, rdd, **kwargs)
    168         custom = self.custom_objects
    169 
--> 170         yaml = self._master_network.to_yaml()
    171         init = self._master_network.get_weights()
    172         parameters = rdd.context.broadcast(init)

~/.pyenv/versions/3.6.13/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in to_yaml(self, **kwargs)
   2298     """
   2299     raise RuntimeError(
-> 2300         'Method `model.to_yaml()` has been removed due to security risk of '
   2301         'arbitrary code execution. Please use `model.to_json()` instead.'
   2302     )
"

**Comment by danielenricocahall** [comment]
Thank you! I'll look into this now.

**Comment by danielenricocahall** [comment]
Addressed in the latest (3.0.0) release. Let me know how it works!
