### ISSUE TITLE
Issues on installing version 3.0.0

### ISSUE THREAD

**Issue by aabbcc002** [maxpumperla/elephas#195]
when installing version 3.0.0 using pip, error message show: 
ERROR: Could not find a version that satisfies the requirement h5py==3.3.0 (from elephas) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0, 3.0.0rc1, 3.0.0, 3.1.0)
ERROR: No matching distribution found for h5py==3.3.0

**Comment by danielenricocahall** [comment]
Which Python version are you running?

**Comment by aabbcc002** [comment]
> Which Python version are you running?

python 3.6.13

**Comment by guidiandrea** [comment]
I was able to install h5py==3.3.0 by downloading the wheel, python==3.7.9.

The problem is that when I try installing Elephas, Tensorflow 2.6 is first installed and it downgrades h5py to 3.1.0

**Comment by danielenricocahall** [comment]
@aabbcc002 Elephas requires Python 3.7+, ideally Python3.8+. Please try with one of those versions and let me know!
