### ISSUE TITLE
Dose elephas support cutom loss cuntion or custom optimizer?

### ISSUE THREAD

**Issue by wangbingnan136** [maxpumperla/elephas#197]

**Comment by danielenricocahall** [comment]
Yes! As of 1.2.0, custom loss functons are supported: https://github.com/maxpumperla/elephas/releases/tag/1.2.0. Here's an example of using a custom activation: https://github.com/maxpumperla/elephas/blob/master/tests/test_ml_model.py#L231. You should be able to do something similar for custom losses and custom optimizers.
