### ISSUE TITLE
Elephas and RNN

### ISSUE THREAD

**Issue by qiangsiwei** [maxpumperla/elephas#21]
I have a few concerns about using elephas to implement RNN.
The first is whether the Graph model can be used?
The second is how to deal with variable sequence length in training set? Does it currently support this?
The third is how to save and load model weight? Is it the same with the one in Keras? 
Thanks! Looking forward to your reply.

**Comment by maxpumperla** [comment]
Hi @qiangsiwei, thanks for your questions.

1. Graph models are only supported, if you don't have multiple inputs or outputs (which I have to change, there's already an issue for that)
2. Regarding what's happening internally in a model, you can just use keras.
3. An elephas model in its basic version consists of a SparkContext and a Keras model. So you can just store/load the keras model and as long as you have an SC, you're good to go.

Just one last thing, for now you have to use keras 0.3 with elephas, as I didn't have time to port to 1.0

Hope this helps!

**Comment by qiangsiwei** [comment]
Great! Thanks, btw your code is very clear and easy to understand!

**Comment by maxpumperla** [comment]
Thank you, I'm glad to hear that!

**Comment by Vamshi26** [comment]
Hey , Thanks with the code man , its a great stuff.
But recently i came to know that , i cant use elephas multiple times in same instance.
Let me clear you here,
i have an application , there i can run two nn models at a time ,internally i am using elphas to distirbute it .
But unfortunately , I can't run two models at at time, Since elphas is binding with the PORT 5000, until it free , i cant use it further,

Please help me on this 

Mate,
Vamsi.P

**Comment by saikswaroop** [comment]
> Hi @qiangsiwei, thanks for your questions.
> 
>     1. Graph models are only supported, if you don't have multiple inputs or outputs (which I have to change, there's already an issue for that)
> 
>     2. Regarding what's happening internally in a model, you can just use keras.
> 
>     3. An elephas model in its basic version consists of a SparkContext and a Keras model. So you can just store/load the keras model and as long as you have an SC, you're good to go.
> 
> 
> Just one last thing, for now you have to use keras 0.3 with elephas, as I didn't have time to port to 1.0
> 
> Hope this helps!

any  fix for this in the latest versions ??
