### ISSUE TITLE
spark_model.py determine_master always return 127.0.0.1

### ISSUE THREAD

**Issue by nuri428** [maxpumperla/elephas#23]
hi there

i runing spark on virtual machine 

when spark_model.py: determine_master always return 127.0.0.1 

so i use like this 

def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

def determine_master():
        '''
        Get URL of parameter server, running on master
        '''
        #master_url = socket.gethostbyname(socket.gethostname()) + ':5000'
        master_url = get_ip_address('eth0')+':5000'
        #print "master_url:" master_url
        return master_url

**Comment by sshilpika** [comment]
I was facing this issue too but I realized I was using the SparkMLlibModel. The determine_master method wasn't being called so I switched to using SparkModel which worked.

**Comment by saikat-roy** [comment]
@sshilpika : I tried using SparkModel for this but it started throwing a "HTTPError: HTTP Error 503: Service Unavailable" error. Have you faced anything similar?
