### ISSUE TITLE
Understanding matrix as features

### ISSUE THREAD

**Issue by Davidott4** [maxpumperla/elephas#27]
I have a convolutional network that runs on a 2D numpy matrix, which I'm trying to move onto Spark/Elephas.

The pipeline is numpy array ->  pyspark.mllib.linalg.DenseMatrix -> Convolutional Network prediction.

This gives me the error:
    TypeError: Cannot convert type <class 'pyspark.mllib.linalg.DenseMatrix'> into Vector

Can a multidimensional numpy array be formatted in a way that that a Keras Convolution1D or Convolution2D layers will understand them?

**Comment by danielenricocahall** [comment]
Is this still an issue?
