### ISSUE TITLE
installation problem with anaconda python

### ISSUE THREAD

**Issue by moshiour** [maxpumperla/elephas#28]
Hello,
I got installation issues of elephas on anaconda python: 

Collecting hyperopt (from hyperas->elephas)
  Downloading hyperopt-0.0.2.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 3.1MB/s 
    Complete output from command python setup.py egg_info:
    DEBUG:root:distribute_setup.py not found, defaulting to system setuptools
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-f5ry_pgi/hyperopt/setup.py", line 119, in <module>
        if package_data is None: package_data = find_package_data(packages)
      File "/private/tmp/pip-build-f5ry_pgi/hyperopt/setup.py", line 102, in find_package_data
        for subdir in find_subdirectories(package):
      File "/private/tmp/pip-build-f5ry_pgi/hyperopt/setup.py", line 73, in find_subdirectories
        subdirectories = os.walk(package_to_path(package)).next()[1]
    AttributeError: 'generator' object has no attribute 'next'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-f5ry_pgi/hyperopt/
# 

Thank you in advance
Moshiour

**Comment by kmader** [comment]
You can pre-install the latest version of ```hyperopts``` which has fixed this to get around this issue (it is a Python 3.4) problem.
```
pip install https://github.com/hyperopt/hyperopt/archive/master.zip
``` 
Before running 
```
pip install elephas
```

**Comment by maxpumperla** [comment]
Please upgrade your hyperopt version, I made it fully py3 compatible a while ago. Thanks!
