### ISSUE TITLE
Pip not installing the entire module in the python dist-packages

### ISSUE THREAD

**Issue by vyassu** [maxpumperla/elephas#3]
The command pip install elephas is not installing the entire repository as mentioned in github. Folders like ml,mlib and utils are missing

**Comment by maxpumperla** [comment]
Version 0.2 now released to pip, please let me know if it works. Make sure to have the latest keras & theano versions. Thanks for the feedback.

**Comment by ansrivas** [comment]
Hi, 
I think this problem still persists .

The setup.py includes just [elephas] so its not able to discover the subpackages. May be you need to include this in your setup.py 

https://github.com/ansrivas/elephas/commit/5cfdd7817d2a0a363db12bc0ccfcf618bf2a66bb

**Comment by maxpumperla** [comment]
Yes, thank you. Should work now in 0.2.1.
