### ISSUE TITLE
get_hyperopt_model_string needs extra parameters

### ISSUE THREAD

**Issue by emmjaykay** [maxpumperla/elephas#35]
I built up a newer system using the directions in I have [created](https://github.com/emmjaykay/docker-gpu-spark-keras-hyperopt-hyperas-elephas) and I noticed a newer error message about this function needing more parameters.

The ones I did add seemed to alleviate the issue though I'm not comfortable with the defaults. They are similar to the ones I have seen in the code base.

> elephas/hyperparam.py
>  @@ -17,7 +17,7 @@ def __init__(self, sc, num_workers=4):
>          self.num_workers = num_workers
>  
>      def compute_trials(self, model, data, max_evals):
> -        model_string = get_hyperopt_model_string(model, data)
> +        model_string = get_hyperopt_model_string(model, data, notebook_name=None, verbose=True, stack=3)
>          bc_model = self.spark_context.broadcast(model_string)
>          bc_max_evals = self.spark_context.broadcast(max_evals)

**Comment by maxpumperla** [comment]
@emmjaykay your link does not seem to work, but I'd be interested to read what you have there. 

You're right, I need to update elephas with regards to the latest version of hyperas. I wanted to do this next in any case, so thanks for letting me know there's interest.

**Comment by emmjaykay** [comment]
@maxpumperla That would be fantastic. I'd be more than willing to help out with that if you give some guidance. I have extreme interest in hyperparameter optimization for keras models. 

Here is what I meant to link: https://github.com/emmjaykay/docker-gpu-spark-keras-hyperopt-hyperas-elephas

The updating you mentioned might also explain why the hyperparameter_optimization.py example is crashing. I'll create another issue. I very much would like to get this fixed and I am willing to put in the work. :)

**Comment by maxpumperla** [comment]
@emmjaykay that sounds great. I'll have to see how much work it actually is (assume  it's fine) and will come back to you if there's anything you might help out with. Thanks

**Comment by jrubin01** [comment]
@maxpumperla Thank you for your work and this great project. 
+1 for a resolution to this issue. Would be great to do use elephas to perform hyperparameter optimization with latest hyperas. Cheers.

**Comment by AlexSnet** [comment]
+1

**Comment by aalloul** [comment]
+1 for this issue

**Comment by chenhuims** [comment]
+1

**Comment by abanskota** [comment]
@maxpumperla and @emmjaykay what was the way around of this issue? I am getting the same error as below. I installed the latest version of elephas and hyperopt from the git repositories. Please let me know how you resolve the issue. Thanks!

`TypeError: get_hyperopt_model_string() missing 4 required positional arguments: 'functions', 'notebook_name', 'verbose', and 'stack'`

**Comment by maxpumperla** [comment]
fixed on master
