### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by vyassu** [maxpumperla/elephas#4]
It seems that while executing train method AsynchronousSparkWorker, "X_train" numpy array has zero length, due to which some of the tasks are failing with the error mentioned in the subject line. I have fixed the same on my local system by incorporating the below mentioned lines inside the train method

if len(X_train)==0:
           return

**Comment by maxpumperla** [comment]
Unfortunately, I can't reproduce the error on my side, but I see the problem with Spark not evenly distributing load sometimes. Your suggestion is in, would you mind checking if it works for you? Thanks for your help!
