### ISSUE TITLE
How to show log on every epoch ?

### ISSUE THREAD

**Issue by kingychiu** [maxpumperla/elephas#40]
I would like to observe the status after each epoch, while the estimator.set_verbosity function is not working.

**Comment by danielenricocahall** [comment]
This is related to https://github.com/maxpumperla/elephas/issues/131 - I may look into that for an upcoming release.

**Comment by danielenricocahall** [comment]
Moved this issue to the new fork: https://github.com/danielenricocahall/elephas/issues/9. Closing for now but still on the radar!
