### ISSUE TITLE
The rdd is not distributed very well by repartition in spark_model.py

### ISSUE THREAD

**Issue by chungfu27** [maxpumperla/elephas#41]
@maxpumperla I found my training rdd is not be partitioned very well and I commented "repartition(self.num_workers)" in spark_model.py and use random mechanism to do repartiton at to_simple_rdd or in my pyspark script.
Therefore, my training data is distributed on my exectuors very well.
Could you provide the entry point to do repartition at rdd_utils.py, not in spark_model.py?

**Comment by maxpumperla** [comment]
@chungfu27 yes, that's a good point. we should move this out. not sure we need an explicit helper method, though. you can call repartition at any point you want, no?

**Comment by chungfu27** [comment]
@maxpumperla yes, I think this helper method to help user to do their repartiton would be okay!
Further, maybe some training data will have data-skew problem, so I think this helper method could provide lambda function to let user to write their partitioner then do repartiton at last.
