### ISSUE TITLE
error when importing elephas

### ISSUE THREAD

**Issue by kirk86** [maxpumperla/elephas#43]
Hi, thanks a lot for your great work. I was wondering if you could give me some hints on this error, which happens every time that I import elephas.

```
ImportError: No module named utils.rdd_utils
```

Also in the front page readme here on github the example indicated below, I think the line with the arrow contains an argument not used any more which is the `num_workers`? Am I right?

```
from elephas.spark_model import SparkModel
from elephas import optimizers as elephas_optimizers

adagrad = elephas_optimizers.Adagrad()
spark_model = SparkModel(sc,model, optimizer=adagrad, frequency='epoch', mode='asynchronous', num_workers=2)
---> spark_model.train(rdd, nb_epoch=20, batch_size=32, verbose=0, validation_split=0.1, num_workers=8)
```

Another thing that I noticed is that by default the import of elephas uses theano as backend instead of tensorflow even if you have explicitly specified tensorflow in your .keras/keras.json

Does elephas play nice with `tensorflow` and `keras`  1.2.2 ?

Cheers!

**Comment by audac1ty** [comment]
Having the same issue. Can anybody assist?

**Comment by maxpumperla** [comment]
install elephas from master and check out `requirements.txt` for dependencies. thanks!
