### ISSUE TITLE
Tasks are not being distributed through Spark Cluster

### ISSUE THREAD

**Issue by milad181** [maxpumperla/elephas#44]
Hi there,

I have been trying to test the elephas using the mnist_mlp_spark.py example using a spark cluster with 2 slaves and apparently the model/parameter training is only being handled by the master node (driver) and slaves are doing nothing in this process. 

I have monitored the memory usage of worker nodes and no changes while the model is being run.

I am wondering if the elephas only works with the spark in a Standalone mode or perhaps I am missing something.

Note that I have used the mnist_mlp_spark and I only changed setMaster('local[8]') to setMaster('YARN') and ran the spark-submit command in a cluster mode.

**Comment by jeffonia** [comment]
Which version of your elephas?
I found that version 0.3 and before doesn't compile the model which is deserialized from yaml file, that will cause the error like "RuntimeError: The model needs to be compiled before being used". Well, this is a big problem as i can see, for distributing your model to worker nodes to train or evaluate. Follow this commit: eee20168ca7883c1e8a19a28bae4b7bdafbc0245, you'll see. Btw, which version of keras and spark you're using?

**Comment by milad181** [comment]
Thanks for your prompt response. I have been using your latest version available at the Github repository. I am also using the Keras 1.2.1 as the version 2 is not fully compatible with elephas. Also I use spark 2.1.

The model is compiled before creating the sparkModel and I do not get any error while I am running it. It just apparently does not send the parameters to workers. Can you kindly send me an example of how to distribute the spark model between workers? 

Below is the part of my code where 

`conf = SparkConf().setAppName('Elephas_App').setMaster('yarn-client')
sc = SparkContext(conf=conf)

#Model will be built here and then the below code.

adam = Adam()
model = Model(img_input, y)
model.compile(loss='mean_squared_error',optimizer=adam)

rdd = to_simple_rdd(sc, image2, image2)
adagrad = elephas_optimizers.Adagrad()
spark_model = SparkModel(sc, yaml, model, optimizer=adagrad, frequency='epoch', mode='asynchronous', num_workers=8 ,master_loss='mse')
spark_model.train(rdd, nb_epoch=20, batch_size=32, verbose=0)
model.save('my_model_2.h5')`

**Comment by mthmn20** [comment]
I had this issue too and was able to get Elephas/Spark to evenly distribute the work amongst workers by setting num_workers really high when initializing SparkModel, e.g. setting num_workers to 40 when my actual number of workers was 2.
