### ISSUE TITLE
Java heap error in while using a relatively small dataset

### ISSUE THREAD

**Issue by milad181** [maxpumperla/elephas#45]
Hi,

I am training a CNN model using elephas to distribute the parameter training and I am getting "out of memory - Spark java.lang.OutOfMemoryError: Java heap space" error. 

This model uses a dataset of 2.6 GB and I am using a spark cluster with 2 workers. all the nodes have 15 GB of RAM and 8 cores of CPU. I use the following command to run the program.

spark-submit  --num-executors 8 --executor-cores 5 --executor-memory 4.5G ./myprogram.py

And before getting to the updating the parameter transactions I get the OutOfMemoryError. Can you suggest how much memory should I allocate?

Note that I have tried this with different values in num_worker and got the same error.

**Comment by Zsomx** [comment]
+1

**Comment by brucebismarck** [comment]
+1 Need to improve memory management

**Comment by shan1322** [comment]
i get this error when increase training set size from 100000 rows to 200000  
what can i do improve memory management i have 50gb ram for all executors and driver

**Comment by danielenricocahall** [comment]
Is this still an issue for anyone?

**Comment by danielenricocahall** [comment]
Closing this for now.
