### ISSUE TITLE
The spark task is stuck even training job finished

### ISSUE THREAD

**Issue by chungfu27** [maxpumperla/elephas#46]
Hi @maxpumperla ,
I encounter unexplainable problem, my spark task is stuck when fit() or train_on_batch() finished.
First, I think maybe the lock results in this problem in "asynchronous" mode but even I try "hogwhild" mode and my spark task is still stuck.
What do you think there have the other reason to cause this problem?

**Comment by maxpumperla** [comment]
hey @chungfu27, I have to further investigate this. very likely the parameter server does not properly shut down (used in both async and hogwild). Do you experience similar problems with synchronous mode?

**Comment by chungfu27** [comment]
Hi @maxpumperla ,
There is no problem in the synchronous mode.
And I added "timeout" in urlopen function of "put_deltas_to_server/get_server_weights" and added error handler for timeout exception to workaround this.
I think the parameter server maybe miss the request and timeout is infinite to result in that the spark driver is always waitting for the job finished.

**Comment by maxpumperla** [comment]
hmm, sounds plausible. I'll have to investigate how to cancel the request and resume in this case. If you have an idea how to resolve this, please share! thanks

**Comment by rsk2327** [comment]
Hi. Have you been able to find a solution for this yet? I dont face issues while using hogwild, but async and sync versions give issues at times. I see in the logs that the workers have sent back data to the driver. So I am not sure why the model gets stuck there.

**Comment by danielenricocahall** [comment]
Is this still an issue?

**Comment by danielenricocahall** [comment]
Closing this for now.
