### ISSUE TITLE
Is there Spark 2 support?

### ISSUE THREAD

**Issue by verarim** [maxpumperla/elephas#49]
If not, is it planned for any near future? Thanks!

**Comment by bzhong2** [comment]
+1

**Comment by maxpumperla** [comment]
for the very simple example, just using RDDs, there is  spark 2 support, since this interface hasn't changed. for all other use cases I still have to migrate to spark 2. hope to get around to doing this this month, but I can't promise anything.

**Comment by maxpumperla** [comment]
Sorry, have to further postpone this to end of July.

**Comment by teemukinnunen** [comment]
I am also looking forward to see support for Spark 2.x including dataframes. Keep up the good work @maxpumperla !

**Comment by maxpumperla** [comment]
spark2 is definitely supported, check out updated examples and tests.
