### ISSUE TITLE
predict_classes method missing in SparkModel class

### ISSUE THREAD

**Issue by vyassu** [maxpumperla/elephas#5]
Sequential model of Keras provides a method predict_classes that returns the label for a given test feature. The below mentioned lines of code would help to achieve the desired result

def predict_classes(self,data):
        return self.master_network.predict_classes(data)

**Comment by maxpumperla** [comment]
OK, I added this because it's been requested. I should note, though, that I'd rather not replicate the interface of keras itself, as you can just get the underlying model back.
