### ISSUE TITLE
Can i use elephas to enhance the prediction ?

### ISSUE THREAD

**Issue by alaeddinechhima** [maxpumperla/elephas#55]
I want to enhance prediction performance of my keras model so i am wondering if elephas could help me ?

**Comment by maxpumperla** [comment]
closing as duplicate of #54

**Comment by danielenricocahall** [comment]
Officially added support for parallel prediction and evaluation in 1.1.0: https://github.com/maxpumperla/elephas/releases/tag/1.1.0 feel free to play with it and let me know how it goes!
