### ISSUE TITLE
save and load keras model to/from HDFS

### ISSUE THREAD

**Issue by shaygeller** [maxpumperla/elephas#56]
Hello,
Im new to elephas and Keras. 
Is there a possibility to save the trained model to HDFS and load it later to make predictions?
Thanks

**Comment by FierceKing** [comment]
same question here

**Comment by FierceKing** [comment]
hi @shaygeller , I found a very straight forward way by might be the easiest way to solve this problem.
just save the file using model.save('filename.h5'), then open it and save it again using functions that support HDFS file system. for example.

model.save('model.h5')
	# a = model.get_config()
	with open('model.h5', 'rb') as f:
		f_content = f.read()
	tf.gfile.FastGFile(oss_prefix + 'model1.h5', 'wb').write(f_content)

**Comment by marvinxu-free** [comment]
> hi @shaygeller , I found a very straight forward way and might be the easiest way to solve this problem.
> just save the file using model.save('filename.h5'), then open and save it again using functions that support HDFS file system. for example.
> 
> ```
> model.save('model.h5')
> with open('model.h5', 'rb') as f:
> 	f_content = f.read()
> tf.gfile.FastGFile(HDFS_prefix + 'model1.h5', 'wb').write(f_content)
> ```

what HDFS mean is hadoop distribution file system.

**Comment by maxpumperla** [comment]
right. it's a difficult question whether elephas should provide functionality like this. I'm open to adding features like that, but you could also argue that "how do I store stuff in my DB" is somewhat of a separate issue.

anyway, thanks for providing that snippet @FierceKing

**Comment by 372046933** [comment]
Actually, you can use Keras with `model.save('hdfs://NAMENODE_IP:NAMENODE_PORT/PATH_TO_MODEL')`. And if you want to specify user name of HDFS, specify `HADOOP_USER_NAME` in the environment. All the rest is taken care by the framework

**Comment by Alwaysproblem** [comment]
> Actually, you can use Keras with `model.save('hdfs://NAMENODE_IP:NAMENODE_PORT/PATH_TO_MODEL')`. And if you want to specify user name of HDFS, specify `HADOOP_USER_NAME` in the environment. All the rest is taken care by the framework

It turns out that it is not working on the hdfs path with model.save and the program will be stuck.

tensorflow 2.1.0
