### ISSUE TITLE
ImportError: cannot import name keyword_only

### ISSUE THREAD

**Issue by nagamanojk** [maxpumperla/elephas#60]
Hi I'm getting the following error, with older Spark 2.0.1 
I also observed that keyword_only is not defined in under pyspark.ml.util
The definition is available at spark/python/pyspark/__init__.py
so I think is sufficient to have from "pyspark import keyword_only"

Traceback (most recent call last):
  File "/home/jayendran/elephas-master/examples/ml_mlp.py", line 10, in <module>
    from elephas.ml_model import ElephasEstimator
  File "/usr/local/lib/python2.7/dist-packages/elephas/ml_model.py", line 6, in <module>
    from pyspark.ml.util import keyword_only
ImportError: cannot import name keyword_only

Can you please fix this issue?
Thanks,
Manoj

**Comment by Zaidihouda** [comment]
Hello,

did you find a solution to this problem, I have the same concern

Thank you
HZ

**Comment by maxpumperla** [comment]
this has been fixed a while ago. need to get out a new version of elephas soon.
