### ISSUE TITLE
Using elephas as per example failing.

### ISSUE THREAD

**Issue by komal436** [maxpumperla/elephas#67]
from keras.datasets import mnist
from pyspark import SparkContext
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from elephas.utils.rdd_utils import to_simple_rdd
from keras.datasets import mnist

sc = SparkContext()
(x_train, y_train), (x_test, y_test) = mnist.load_data()
rdd = to_simple_rdd(sc, x_train, y_train)

model = Sequential()
model.add(Dense(128, input_dim=784))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer=SGD())
from elephas.spark_model import SparkModel
from elephas import optimizers as elephas_optimizers

adagrad = elephas_optimizers.Adagrad()
spark_model = SparkModel(sc,model, optimizer=adagrad, frequency='epoch', mode='asynchronous', num_workers=2)
spark_model.train(rdd, nb_epoch=20, batch_size=32, verbose=0, validation_split=0.1)

while training model, the spark context looks like being used in the workers. Can you suggest what I am missing?
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-16-7cb36f94621b> in <module>()
      4 adagrad = elephas_optimizers.Adagrad()
      5 spark_model = SparkModel(sc,model, optimizer=adagrad, frequency='epoch', mode='asynchronous', num_workers=2)
----> 6 spark_model.train(rdd, nb_epoch=20, batch_size=32, verbose=0, validation_split=0.1)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\elephas\spark_model.py in train(self, rdd, nb_epoch, batch_size, verbose, validation_split)
    195 
    196         if self.mode in ['asynchronous', 'synchronous', 'hogwild']:
--> 197             self._train(rdd, nb_epoch, batch_size, verbose, validation_split, master_url)
    198         else:
    199             print("""Choose from one of the modes: asynchronous, synchronous or hogwild""")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\elephas\spark_model.py in _train(self, rdd, nb_epoch, batch_size, verbose, validation_split, master_url)
    206         self.master_network.compile(optimizer=self.master_optimizer, loss=self.master_loss, metrics=self.master_metrics)
    207         if self.mode in ['asynchronous', 'hogwild']:
--> 208             self.start_server()
    209         yaml = self.master_network.to_yaml()
    210         train_config = self.get_train_config(nb_epoch, batch_size,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\elephas\spark_model.py in start_server(self)
    123         ''' Start parameter server'''
    124         self.server = Process(target=self.start_service)
--> 125         self.server.start()
    126 
    127     def stop_server(self):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py in start(self)
    103                'daemonic processes are not allowed to have children'
    104         _cleanup()
--> 105         self._popen = self._Popen(self)
    106         self._sentinel = self._popen.sentinel
    107         # Avoid a refcycle if the target function holds an indirect

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyspark\context.py in __getnewargs__(self)
    304         # This method is called when attempting to pickle SparkContext, which is always an error:
    305         raise Exception(
--> 306             "It appears that you are attempting to reference SparkContext from a broadcast "
    307             "variable, action, or transformation. SparkContext can only be used on the driver, "
    308             "not in code that it run on workers. For more information, see SPARK-5063."

Exception: It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.

**Comment by maxpumperla** [comment]
all examples work on master. I added them to unit tests as well.
