### ISSUE TITLE
ImportError: No module named theano_utils for elephas_optimizer import

### ISSUE THREAD

**Issue by mitomm** [maxpumperla/elephas#7]
First, thanks for the bringing Keras to Spark.

Seems very interesting.

I'm trying to implement the example from the README.md but I get the following error:

Traceback (most recent call last):
  File "..pathToFile/File.py", line 12, in <module>
    from elephas import optimizers as elephas_optimizers
  File "/Users/XXX/anaconda/lib/python2.7/site-packages/elephas/optimizers.py", line 11, in <module>
    from keras.utils.theano_utils import shared_zeros, shared_scalar, floatX
ImportError: No module named theano_utils

I also tried changing keras backend to TensorFlow. However Elephas is still looking (and cannot find) "theano_utils". 

Any ideas on why this doesn't work?

Thanks

**Comment by maxpumperla** [comment]
Yes, you're absolutely right, thanks for this. The reason this breaks is that the latest release of Keras, introducing backends, *removed* the file theano_utils, as it is backend-specific. I will fix this and make a new minor release as soon as I find the time. Until then, would you please consider using Keras version 0.2.0 to run the example?

Then this one should work for you:
https://github.com/maxpumperla/elephas/blob/master/examples/mnist_mlp_spark.py

**Comment by maxpumperla** [comment]
Hi @mitomm, just released elephas 0.2.2 to revolve all theano/backend related issues. Does this work as expected for you?

**Comment by mitomm** [comment]
Hi @maxpumperla, yes, the error is gone now. Thanks for the quick fix.

**Comment by maxpumperla** [comment]
Sure, no problem. Thanks!
