### ISSUE TITLE
ImportError: cannot import name 'keyword_only'

### ISSUE THREAD

**Issue by gauravyeole** [maxpumperla/elephas#70]
ImportError                               Traceback (most recent call last)
<ipython-input-26-08c632204ef8> in <module>()
      7 from keras.utils import np_utils, generic_utils
      8 
----> 9 from elephas.ml_model import ElephasEstimator
     10 from elephas import optimizers as elephas_optimizers
     11 

/usr/local/lib/python3.5/dist-packages/elephas/ml_model.py in <module>()
      4 
      5 from pyspark.ml.param.shared import HasInputCol, HasOutputCol, HasFeaturesCol, HasLabelCol
----> 6 from pyspark.ml.util import keyword_only
      7 from pyspark.sql import Row
      8 from pyspark.ml import Estimator, Model

ImportError: cannot import name 'keyword_only'

I guess there is error in statement elephas/elephas/ml_model.py python file. 
I am running on Spark 2.2.0

**Comment by gauravyeole** [comment]
Please pull the latest commit to the repository.

**Comment by EvanZ** [comment]
Is this still an issue? I'm getting the same error and am on elephas 0.3.

**Comment by maxpumperla** [comment]
it's fixed on master. will have a new release soon

**Comment by buddha314** [comment]
Is there a work-around in the mean time?

**Comment by maxpumperla** [comment]
install from master...

**Comment by prasannapkr** [comment]
How do you go about installing from the master?

**Comment by maxpumperla** [comment]
you type "how to install python project from github master" into altavista

**Comment by prasannapkr** [comment]
Did that, now i have code from master and I get the error "AttributeError: 'ElephasEstimator' object has no attribute 'set_nb_epoch'" and "KeyError: Param(parent='ElephasEstimator_4b3ba5dffab8e221b7af', name='loss', doc='Keras loss')" if I comment the line in my code containing set_nb_epoch.

I am running the code provided by your notebook in https://github.com/maxpumperla/elephas/blob/master/examples/Spark_ML_Pipeline.ipynb

**Comment by maxpumperla** [comment]
@prasannapkr sorry, it's _extremely_ difficult for me to keep track of comments in closed issues.

Yeah, I didn't get around to updating the notebook yet. I think the new setter is `set_epochs` now (reflecting keras' move from `nb_epoch` to `epochs`. You'll find these methods here:

https://github.com/maxpumperla/elephas/blob/master/elephas/ml/params.py
