### ISSUE TITLE
The model is fitted more than nb_epoch times

### ISSUE THREAD

**Issue by waniss** [maxpumperla/elephas#77]
Hi,
I am running a code on a cluster with 3 workers. If i set for example Nb_epoch to 30, it doesn't stop, but it runs again 3 or 4 times 30 epochs. Can anyone help with this issue please ?
```

2101/2101 [==============================] - 10s 5ms/step - loss: 0.6103 - acc: 0.7444 - val_loss: 1.1255 - val_acc: 0.5427
Epoch 30/30

 128/2101 [>.............................] - ETA: 8s - loss: 0.4757 - acc: 0.8281
 256/2101 [==>...........................] - ETA: 8s - loss: 0.5443 - acc: 0.7891
 384/2101 [====>.........................] - ETA: 7s - loss: 0.5503 - acc: 0.7812
 512/2101 [======>.......................] - ETA: 7s - loss: 0.5372 - acc: 0.7793
 640/2101 [========>.....................] - ETA: 6s - loss: 0.5590 - acc: 0.7609
 768/2101 [=========>....................] - ETA: 5s - loss: 0.5685 - acc: 0.7630
 896/2101 [===========>..................] - ETA: 5s - loss: 0.5730 - acc: 0.7634
1024/2101 [=============>................] - ETA: 4s - loss: 0.5728 - acc: 0.7705
1152/2101 [===============>..............] - ETA: 4s - loss: 0.5794 - acc: 0.7622
1280/2101 [=================>............] - ETA: 3s - loss: 0.5891 - acc: 0.7578
1408/2101 [===================>..........] - ETA: 3s - loss: 0.5923 - acc: 0.7550
1536/2101 [====================>.........] - ETA: 2s - loss: 0.5942 - acc: 0.7513
1664/2101 [======================>.......] - ETA: 1s - loss: 0.5953 - acc: 0.7524
1792/2101 [========================>.....] - ETA: 1s - loss: 0.5938 - acc: 0.7500
1920/2101 [==========================>...] - ETA: 0s - loss: 0.5868 - acc: 0.7552
2048/2101 [============================>.] - ETA: 0s - loss: 0.5930 - acc: 0.7524
2101/2101 [==============================] - 10s 5ms/step - loss: 0.5914 - acc: 0.7544 - val_loss: 1.2075 - val_acc: 0.5128
Train on 2101 samples, validate on 234 samples
Epoch 1/30
```

**Comment by maxpumperla** [comment]
which model do you use, which version and with which parameters? Can you create a gist, please?

**Comment by waniss** [comment]
Hi, in both i'm using the latest version, with python 2.7.

So i checked the code and i find out that, the problem was in the AsynchronousSparkWorker class.
``       if self.frequency == 'epoch':
            for epoch in range(nb_epoch):
                weights_before_training = get_server_weights(self.master_url)
                model.set_weights(weights_before_training)
                self.train_config['epochs'] = 1
                if x_train.shape[0] > batch_size:
                    model.fit(x_train, y_train, **self.train_config)
                weights_after_training = model.get_weights()
                deltas = subtract_params(weights_before_training, weights_after_training)
put_deltas_to_server(deltas, self.master_url)``

in Keras : 
> Warning: The `nb_epoch` argument in `fit` has been renamed `epochs`
So there is some confusion, it's self.train_config['nb_epochs'] that is used for Keras model.fit function. 
Finally if nb_epoch is set to 20, it's rans model.fit 20 times, and 20 epoch for each

**Comment by maxpumperla** [comment]
yeah, `nb_epochs` is still from keras 1, but it's only a warning. should be fine. I'll have to update this at some point (feel free to send a PR, if you find the time).

ok, so each worker runs for 20 epochs, meaning the master gets 20 * num_workers updates. Do you expect this to work differently?

**Comment by waniss** [comment]
Well, it's not fine, because it's `nb_epoch` that is compiled, the `self.train_config['epochs'] = 1` is useless.
Each worker runs for 20 epochs, but the master will be updated at the end.  So, in total we'll have 400 epochs (20 updates from the loop, and for each again 20 epochs for `model.fit`). Is it correct ?

**Comment by maxpumperla** [comment]
sorry, I misinterpreted this at first. so, `self.train_config['epochs'] = 1` works for keras 2 models. so you're using keras 1 still? I'm not sure we can ensure full backward compatibility.

If it's OK to switch, do as the keras warning says and rename your epochs.

**Comment by waniss** [comment]
i'm using Keras 2.1.3.
i'm really sorry, but i'm little bit confused, so the `self.train_config['epochs'] = 1 ` is used to train the keras model : `model.fit(x_train, y_train, **self.train_config)` just with one epoch ? 

This is an example, is this how the result shoud be ? 
`Train on 1611 samples, validate on 179 samples
Epoch 1/1
***** Master Updated at Elephas Epoch : 0  ******
Train on 1611 samples, validate on 179 samples
Epoch 1/1
***** Master Updated at Elephas Epoch : 1  ******
Train on 1611 samples, validate on 179 samples
Epoch 1/1`

**Comment by maxpumperla** [comment]
this should be fixed on master now. please give me feedback if this still causes unexpected behavior. thanks!
