### ISSUE TITLE
elephas with tensorflow only

### ISSUE THREAD

**Issue by MohamedAmineOuali** [maxpumperla/elephas#78]
Hello,
could I use elepha without using keras I want to use it with tensorflow only 

Thank you :)

**Comment by maxpumperla** [comment]
@MohamedAmineOuali that's a cool idea I've been thinking about for a while. Having said that, I don't have time for this prior to June (bc of the book). Keep reminding me! :)

**Comment by danielenricocahall** [comment]
This sounds like an entirely separate project (although a cool one!). I will close this ticket for now.
