### ISSUE TITLE
TypeError: get_hyperopt_model_string() takes exactly 6 arguments (2 given)

### ISSUE THREAD

**Issue by mjaber01** [maxpumperla/elephas#79]
I am trying to run hyperparam_optimization.py on my machine but it gives a runtime error 
TypeError: get_hyperopt_model_string() takes exactly 6 arguments (2 given)!

**Comment by chenhuims** [comment]
I hit the same issue. Hope there is a fix!

**Comment by maxpumperla** [comment]
yeah, so hyperopt and hyperas changed and elephas needs to be adapted. it's just passing more args. you feel like you could do a PR for this?

**Comment by maxpumperla** [comment]
fixed on master
