### ISSUE TITLE
Failure to save model

### ISSUE THREAD

**Issue by EvanZ** [maxpumperla/elephas#98]
I added a line to the ML pipeline example to persist a model:

```
pipeline = Pipeline(stages=[estimator])
fitted_pipeline = pipeline.fit(df)
pipeline.save('/path/to/save/elephas-model')

```

This results in the following error:

`ValueError: ('Pipeline write will fail on this pipeline because stage %s of type %s is not MLWritable', 'ElephasEstimator_45da805673f52c212557', <class 'elephas.ml_model.ElephasEstimator'>)`

This is against:
`git+https://github.com/maxpumperla/elephas.git@cfa51da7d25f35f55728e09561b322c09852d8c0#egg=elephas
`

Is saving models supported?

**Comment by maxpumperla** [comment]
not yet, but it's in the making as we speak. it's in `mp_dl4j` branch with a ton of other cool stuff coming up.

**Comment by EvanZ** [comment]
Ok, great. I will look forward to that. And maybe checkout the branch as well. ;)

**Comment by maxpumperla** [comment]
@EvanZ btw, keras models can be pickled now, PR just got merged. once a new keras release is out, this will make things a little easier.

**Comment by EvanZ** [comment]
@maxpumperla Thanks. I don't want to keep creating issues that might be solved with a new release, so I'll ask this here. I'm trying to build the mnist autoencoder described in the Keras blog:

https://blog.keras.io/building-autoencoders-in-keras.html

I can't quite seem to get it to work, just wondering if there is anything there you might be able to tell me either that is should or should not be able to be implemented in elephas.
